include: package:very_good_analysis/analysis_options.yaml
analyzer:
  errors:
    lines_longer_than_80_chars: ignore
    flutter_style_todos: ignore
    depend_on_referenced_packages: ignore
    omit_local_variable_types: ignore
    invalid_annotation_target: ignore
  exclude:
    - lib/l10n/gen/*
linter:
  rules:
    public_member_api_docs: false
