include: package:very_good_analysis/analysis_options.yaml
analyzer:
  errors:
    lines_longer_than_80_chars: ignore
    flutter_style_todos: ignore
    depend_on_referenced_packages: ignore
    omit_local_variable_types: ignore
    invalid_annotation_target: ignore
    prefer_const_constructors: ignore
    avoid_catches_without_on_clauses: ignore
    avoid_positional_boolean_parameters: ignore
    strict_raw_type: ignore
    directives_ordering: ignore
    avoid_print: ignore
    avoid_equals_and_hash_code_on_mutable_classes: ignore
    cascade_invocations: ignore
  exclude:
    - lib/core/l10n/gen/*
    - lib/*/*.g.dart
    - '*.freezed.dart'
linter:
  rules:
    public_member_api_docs: false
    
