import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:taskly_bloc/domain/models/attention/attention_resolution.dart';
import 'package:taskly_bloc/domain/models/attention/attention_rule.dart';

part 'attention_item.freezed.dart';
part 'attention_item.g.dart';

/// An active attention item for a specific entity
/// Generated by evaluating attention rules against current data
///
/// AttentionItem is the evaluated output - what gets shown to users
/// AttentionRule is the template - how evaluation happens
@freezed
abstract class AttentionItem with _$AttentionItem {
  const factory AttentionItem({
    /// Unique ID for this attention item instance
    required String id,

    /// The rule ID that triggered this item
    required String ruleId,

    /// The rule key for quick lookup
    required String ruleKey,

    /// The rule type (problem, review, allocationWarning)
    required AttentionRuleType ruleType,

    /// The entity ID that triggered this item
    required String entityId,

    /// Entity type (task, project, journal, etc.)
    required AttentionEntityType entityType,

    /// Severity from the rule (info, warning, critical)
    required AttentionSeverity severity,

    /// Human-readable title to display
    required String title,

    /// Human-readable description
    required String description,

    /// Actions available for this item (resolved, snoozed, dismissed)
    required List<AttentionResolutionAction> availableActions,

    /// When this item was detected
    required DateTime detectedAt,

    /// Additional data for display/actions
    Map<String, dynamic>? metadata,
  }) = _AttentionItem;

  factory AttentionItem.fromJson(Map<String, dynamic> json) =>
      _$AttentionItemFromJson(json);
}
