// ignore_for_file: lines_longer_than_80_chars

import 'package:emoji_picker_flutter/emoji_picker_flutter.dart';

/// List of categories of emojis
const List<CategoryEmoji> defaultEmojiSet = [
// ======================================================= Category.SMILEYS
  CategoryEmoji(Category.SMILEYS, [
    Emoji('ðŸ˜€', 'Grinning Face'),
    Emoji('ðŸ˜ƒ', 'Grinning Face With Big Eyes'),
    Emoji('ðŸ˜„', 'Grinning Face With Smiling Eyes'),
    Emoji('ðŸ˜', 'Beaming Face With Smiling Eyes'),
    Emoji('ðŸ˜†', 'Grinning Squinting Face'),
    Emoji('ðŸ˜…', 'Grinning Face With Sweat'),
    Emoji('ðŸ¤£', 'Rolling on the Floor Laughing'),
    Emoji('ðŸ˜‚', 'Face With Tears of Joy'),
    Emoji('ðŸ™‚', 'Slightly Smiling Face'),
    Emoji('ðŸ™ƒ', 'Upside-Down Face'),
    Emoji('ðŸ˜‰', 'Winking Face'),
    Emoji('ðŸ˜Š', 'Smiling Face With Smiling Eyes'),
    Emoji('ðŸ˜‡', 'Smiling Face With Halo'),
    Emoji('ðŸ¥°', 'Smiling Face With Hearts'),
    Emoji('ðŸ˜', 'Smiling Face With Heart-Eyes'),
    Emoji('ðŸ¤©', 'Star-Struck'),
    Emoji('ðŸ˜˜', 'Face Blowing a Kiss'),
    Emoji('ðŸ˜—', 'Kissing Face'),
    Emoji('â˜ºï¸', 'Smiling Face'),
    Emoji('ðŸ˜š', 'Kissing Face With Closed Eyes'),
    Emoji('ðŸ˜™', 'Kissing Face With Smiling Eyes'),
    Emoji('ðŸ˜‹', 'Face Savoring Food'),
    Emoji('ðŸ˜›', 'Face With Tongue'),
    Emoji('ðŸ˜œ', 'Winking Face With Tongue'),
    Emoji('ðŸ¤ª', 'Zany Face'),
    Emoji('ðŸ˜', 'Squinting Face With Tongue'),
    Emoji('ðŸ¤‘', 'Money-Mouth Face'),
    Emoji('ðŸ¤—', 'Hugging Face'),
    Emoji('ðŸ«£', 'Face with Peeking Eye'),
    Emoji('ðŸ¤­', 'Face With Hand Over Mouth'),
    Emoji('ðŸ«¢', 'Face with Open Eyes and Hand Over Mouth'),
    Emoji('ðŸ«¡', 'Saluting Face'),
    Emoji('ðŸ¤«', 'Shushing Face'),
    Emoji('ðŸ« ', 'Melting Face'),
    Emoji('ðŸ¤”', 'Thinking Face'),
    Emoji('ðŸ¤', 'Zipper-Mouth Face'),
    Emoji('ðŸ¤¨', 'Face With Raised Eyebrow'),
    Emoji('ðŸ˜', 'Neutral Face'),
    Emoji('ðŸ«¤', 'Face with Diagonal Mouth'),
    Emoji('ðŸ˜‘', 'Expressionless Face'),
    Emoji('ðŸ˜¶', 'Face Without Mouth'),
    Emoji('ðŸ«¥', 'Dotted Line Face'),
    Emoji('ðŸ˜', 'Smirking Face'),
    Emoji('ðŸ˜’', 'Unamused Face'),
    Emoji('ðŸ™„', 'Face With Rolling Eyes'),
    Emoji('ðŸ˜¬', 'Grimacing Face'),
    Emoji('ðŸ¤¥', 'Lying Face'),
    Emoji('ðŸ˜Œ', 'Relieved Face'),
    Emoji('ðŸ˜”', 'Pensive Face'),
    Emoji('ðŸ¥¹', 'Face Holding Back Tears'),
    Emoji('ðŸ˜ª', 'Sleepy Face'),
    Emoji('ðŸ¤¤', 'Drooling Face'),
    Emoji('ðŸ˜´', 'Sleeping Face'),
    Emoji('ðŸ˜·', 'Face With Medical Mask'),
    Emoji('ðŸ¤’', 'Face With Thermometer'),
    Emoji('ðŸ¤•', 'Face With Head-Bandage'),
    Emoji('ðŸ¤¢', 'Nauseated Face'),
    Emoji('ðŸ¤®', 'Face Vomiting'),
    Emoji('ðŸ¤§', 'Sneezing Face'),
    Emoji('ðŸ¥µ', 'Hot Face'),
    Emoji('ðŸ¥¶', 'Cold Face'),
    Emoji('ðŸ¥´', 'Woozy Face'),
    Emoji('ðŸ˜µ', 'Shocked Face'),
    Emoji('ðŸ˜µâ€ðŸ’«', 'Dizzy Face'),
    Emoji('ðŸ¤¯', 'Exploding Head'),
    Emoji('ðŸ¤ ', 'Cowboy Hat Face'),
    Emoji('ðŸ¥³', 'Partying Face'),
    Emoji('ðŸ˜Ž', 'Smiling Face With Sunglasses'),
    Emoji('ðŸ¤“', 'Nerd Face'),
    Emoji('ðŸ§', 'Face With Monocle'),
    Emoji('ðŸ˜•', 'Confused Face'),
    Emoji('ðŸ˜Ÿ', 'Worried Face'),
    Emoji('ðŸ™', 'Slightly Frowning Face'),
    Emoji('â˜¹ï¸', 'Frowning Face'),
    Emoji('ðŸ˜®', 'Face With Open Mouth'),
    Emoji('ðŸ˜¯', 'Hushed Face'),
    Emoji('ðŸ˜²', 'Astonished Face'),
    Emoji('ðŸ˜³', 'Flushed Face'),
    Emoji('ðŸ¥º', 'Pleading Face'),
    Emoji('ðŸ˜¦', 'Frowning Face With Open Mouth'),
    Emoji('ðŸ˜§', 'Anguished Face'),
    Emoji('ðŸ˜¨', 'Fearful Face'),
    Emoji('ðŸ˜°', 'Anxious Face With Sweat'),
    Emoji('ðŸ˜¥', 'Sad but Relieved Face'),
    Emoji('ðŸ˜¢', 'Crying Face'),
    Emoji('ðŸ˜­', 'Loudly Crying Face'),
    Emoji('ðŸ˜±', 'Face Screaming in Fear'),
    Emoji('ðŸ˜–', 'Confounded Face'),
    Emoji('ðŸ˜£', 'Persevering Face'),
    Emoji('ðŸ˜ž', 'Disappointed Face'),
    Emoji('ðŸ˜“', 'Downcast Face With Sweat'),
    Emoji('ðŸ˜©', 'Weary Face'),
    Emoji('ðŸ˜«', 'Tired Face'),
    Emoji('ðŸ˜¤', 'Face With Steam From Nose'),
    Emoji('ðŸ˜¡', 'Pouting Face'),
    Emoji('ðŸ˜ ', 'Angry Face'),
    Emoji('ðŸ¤¬', 'Face With Symbols on Mouth'),
    Emoji('ðŸ˜ˆ', 'Smiling Face With Horns'),
    Emoji('ðŸ‘¿', 'Angry Face With Horns'),
    Emoji('ðŸ’€', 'Skull'),
    Emoji('â˜ ï¸', 'Skull and Crossbones'),
    Emoji('ðŸ’©', 'Pile of Poo'),
    Emoji('ðŸ¤¡', 'Clown Face'),
    Emoji('ðŸ‘¹', 'Ogre'),
    Emoji('ðŸ‘º', 'Goblin'),
    Emoji('ðŸ‘»', 'Ghost'),
    Emoji('ðŸ‘½', 'Alien'),
    Emoji('ðŸ‘¾', 'Alien Monster'),
    Emoji('ðŸ¤–', 'Robot Face'),
    Emoji('ðŸŽƒ', 'Jack-O-Lantern'),
    Emoji('ðŸ˜º', 'Grinning Cat Face'),
    Emoji('ðŸ˜¸', 'Grinning Cat Face With Smiling Eyes'),
    Emoji('ðŸ˜¹', 'Cat Face With Tears of Joy'),
    Emoji('ðŸ˜»', 'Smiling Cat Face With Heart-Eyes'),
    Emoji('ðŸ˜¼', 'Cat Face With Wry Smile'),
    Emoji('ðŸ˜½', 'Kissing Cat Face'),
    Emoji('ðŸ™€', 'Weary Cat Face'),
    Emoji('ðŸ˜¿', 'Crying Cat Face'),
    Emoji('ðŸ˜¾', 'Pouting Cat Face'),
    Emoji('ðŸ«¶', 'Heart Hands', hasSkinTone: true),
    Emoji('ðŸ‘‹', 'Waving Hand', hasSkinTone: true),
    Emoji('ðŸ¤š', 'Raised Back of Hand', hasSkinTone: true),
    Emoji('ðŸ–ï¸', 'Hand With Fingers Splayed', hasSkinTone: true),
    Emoji('âœ‹', 'Raised Hand', hasSkinTone: true),
    Emoji('ðŸ––', 'Vulcan Salute', hasSkinTone: true),
    Emoji('ðŸ‘Œ', 'OK Hand', hasSkinTone: true),
    Emoji('ðŸ¤Œ', 'Pinched Fingers', hasSkinTone: true),
    Emoji('ðŸ¤', 'Pinching Hand', hasSkinTone: true),
    Emoji('ðŸ«³', 'Palm Down Hand', hasSkinTone: true),
    Emoji('ðŸ«´', 'Palm Up Hand', hasSkinTone: true),
    Emoji('âœŒï¸', 'Victory Hand', hasSkinTone: true),
    Emoji('ðŸ«°', 'Hand with Index Finger and Thumb Crossed', hasSkinTone: true),
    Emoji('ðŸ¤ž', 'Crossed Fingers', hasSkinTone: true),
    Emoji('ðŸ¤Ÿ', 'Love-You Gesture', hasSkinTone: true),
    Emoji('ðŸ¤˜', 'Sign of the Horns', hasSkinTone: true),
    Emoji('ðŸ¤™', 'Call Me Hand', hasSkinTone: true),
    Emoji('ðŸ‘ˆ', 'Backhand Index Pointing Left', hasSkinTone: true),
    Emoji('ðŸ‘‰', 'Backhand Index Pointing Right', hasSkinTone: true),
    Emoji('ðŸ‘†', 'Backhand Index Pointing Up', hasSkinTone: true),
    Emoji('ðŸ–•', 'Middle Finger', hasSkinTone: true),
    Emoji('ðŸ‘‡', 'Backhand Index Pointing Down', hasSkinTone: true),
    Emoji('â˜ï¸', 'Index Pointing Up', hasSkinTone: true),
    Emoji('ðŸ‘', 'Thumbs Up', hasSkinTone: true),
    Emoji('ðŸ‘Ž', 'Thumbs Down', hasSkinTone: true),
    Emoji('âœŠ', 'Raised Fist', hasSkinTone: true),
    Emoji('ðŸ‘Š', 'Oncoming Fist', hasSkinTone: true),
    Emoji('ðŸ¤›', 'Left-Facing Fist', hasSkinTone: true),
    Emoji('ðŸ¤œ', 'Right-Facing Fist', hasSkinTone: true),
    Emoji('ðŸ«²', 'Leftwards Hand', hasSkinTone: true),
    Emoji('ðŸ«±', 'Rightwards Hand', hasSkinTone: true),
    Emoji('ðŸ‘', 'Clapping Hands', hasSkinTone: true),
    Emoji('ðŸ™Œ', 'Raising Hands', hasSkinTone: true),
    Emoji('ðŸ‘', 'Open Hands', hasSkinTone: true),
    Emoji('ðŸ¤²', 'Palms Up Together', hasSkinTone: true),
    Emoji('ðŸ¤', 'Handshake', hasSkinTone: true),
    Emoji('ðŸ™', 'Folded Hands', hasSkinTone: true),
    Emoji('ðŸ«µ', 'Index Pointing at the Viewer', hasSkinTone: true),
    Emoji('âœï¸', 'Writing Hand', hasSkinTone: true),
    Emoji('ðŸ’…', 'Nail Polish', hasSkinTone: true),
    Emoji('ðŸ¤³', 'Selfie', hasSkinTone: true),
    Emoji('ðŸ’ª', 'Flexed Biceps', hasSkinTone: true),
    Emoji('ðŸ¦µ', 'Leg', hasSkinTone: true),
    Emoji('ðŸ¦¶', 'Foot', hasSkinTone: true),
    Emoji('ðŸ‘‚', 'Ear', hasSkinTone: true),
    Emoji('ðŸ‘ƒ', 'Nose', hasSkinTone: true),
    Emoji('ðŸ§ ', 'Brain'),
    Emoji('ðŸ¦´', 'Bone'),
    Emoji('ðŸ‘€', 'Eyes'),
    Emoji('ðŸ‘ï¸', 'Eye'),
    Emoji('ðŸ’‹', 'Kiss Mark'),
    Emoji('ðŸ‘„', 'Mouth'),
    Emoji('ðŸ«¦', 'Biting Lip'),
    Emoji('ðŸ¦·', 'Tooth'),
    Emoji('ðŸ‘…', 'Tongue'),
    Emoji('ðŸ‘¶', 'Baby', hasSkinTone: true),
    Emoji('ðŸ§’', 'Child', hasSkinTone: true),
    Emoji('ðŸ‘¦', 'Boy', hasSkinTone: true),
    Emoji('ðŸ‘§', 'Girl', hasSkinTone: true),
    Emoji('ðŸ§‘', 'Person', hasSkinTone: true),
    Emoji('ðŸ‘¨', 'Man', hasSkinTone: true),
    Emoji('ðŸ§”', 'Man: Beard', hasSkinTone: true),
    Emoji('ðŸ‘±', 'Man: Blond Hair', hasSkinTone: true),
    Emoji('ðŸ‘¨â€ðŸ¦°', 'Man: Red Hair', hasSkinTone: true),
    Emoji('ðŸ‘¨â€ðŸ¦±', 'Man: Curly Hair', hasSkinTone: true),
    Emoji('ðŸ‘¨â€ðŸ¦³', 'Man: White Hair', hasSkinTone: true),
    Emoji('ðŸ‘¨â€ðŸ¦²', 'Man: Bald', hasSkinTone: true),
    Emoji('ðŸ‘©', 'Woman', hasSkinTone: true),
    Emoji('ðŸ‘±â€â™€ï¸', 'Woman: Blond Hair', hasSkinTone: true),
    Emoji('ðŸ‘©â€ðŸ¦°', 'Woman: Red Hair', hasSkinTone: true),
    Emoji('ðŸ‘©â€ðŸ¦±', 'Woman: Curly Hair', hasSkinTone: true),
    Emoji('ðŸ‘©â€ðŸ¦³', 'Woman: White Hair', hasSkinTone: true),
    Emoji('ðŸ‘©â€ðŸ¦²', 'Woman: Bald', hasSkinTone: true),
    Emoji('ðŸ§“', 'Older Person', hasSkinTone: true),
    Emoji('ðŸ‘´', 'Old Man', hasSkinTone: true),
    Emoji('ðŸ‘µ', 'Old Woman', hasSkinTone: true),
    Emoji('ðŸ™â€â™‚ï¸', 'Man Frowning', hasSkinTone: true),
    Emoji('ðŸ™â€â™€ï¸', 'Woman Frowning', hasSkinTone: true),
    Emoji('ðŸ™Žâ€â™‚ï¸', 'Man Pouting', hasSkinTone: true),
    Emoji('ðŸ™Žâ€â™€ï¸', 'Woman Pouting', hasSkinTone: true),
    Emoji('ðŸ™…â€â™‚ï¸', 'Man Gesturing No', hasSkinTone: true),
    Emoji('ðŸ™…â€â™€ï¸', 'Woman Gesturing No', hasSkinTone: true),
    Emoji('ðŸ™†â€â™‚ï¸', 'Man Gesturing OK', hasSkinTone: true),
    Emoji('ðŸ™†â€â™€ï¸', 'Woman Gesturing OK', hasSkinTone: true),
    Emoji('ðŸ’â€â™‚ï¸', 'Man Tipping Hand', hasSkinTone: true),
    Emoji('ðŸ’â€â™€ï¸', 'Woman Tipping Hand', hasSkinTone: true),
    Emoji('ðŸ™‹â€â™‚ï¸', 'Man Raising Hand', hasSkinTone: true),
    Emoji('ðŸ™‹â€â™€ï¸', 'Woman Raising Hand', hasSkinTone: true),
    Emoji('ðŸ™‡â€â™‚ï¸', 'Man Bowing', hasSkinTone: true),
    Emoji('ðŸ™‡â€â™€ï¸', 'Woman Bowing', hasSkinTone: true),
    Emoji('ðŸ¤¦â€â™‚ï¸', 'Man Facepalming', hasSkinTone: true),
    Emoji('ðŸ¤¦â€â™€ï¸', 'Woman Facepalming', hasSkinTone: true),
    Emoji('ðŸ¤·â€â™‚ï¸', 'Man Shrugging', hasSkinTone: true),
    Emoji('ðŸ¤·â€â™€ï¸', 'Woman Shrugging', hasSkinTone: true),
    Emoji('ðŸ‘¨â€âš•ï¸', 'Man Health Worker', hasSkinTone: true),
    Emoji('ðŸ‘©â€âš•ï¸', 'Woman Health Worker', hasSkinTone: true),
    Emoji('ðŸ‘¨â€ðŸŽ“', 'Man Student', hasSkinTone: true),
    Emoji('ðŸ‘©â€ðŸŽ“', 'Woman Student', hasSkinTone: true),
    Emoji('ðŸ‘¨â€ðŸ«', 'Man Teacher', hasSkinTone: true),
    Emoji('ðŸ‘©â€ðŸ«', 'Woman Teacher', hasSkinTone: true),
    Emoji('ðŸ‘¨â€âš–ï¸', 'Man Judge', hasSkinTone: true),
    Emoji('ðŸ‘©â€âš–ï¸', 'Woman Judge', hasSkinTone: true),
    Emoji('ðŸ‘¨â€ðŸŒ¾', 'Man Farmer', hasSkinTone: true),
    Emoji('ðŸ‘©â€ðŸŒ¾', 'Woman Farmer', hasSkinTone: true),
    Emoji('ðŸ‘¨â€ðŸ³', 'Man Cook', hasSkinTone: true),
    Emoji('ðŸ‘©â€ðŸ³', 'Woman Cook', hasSkinTone: true),
    Emoji('ðŸ‘¨â€ðŸ”§', 'Man Mechanic', hasSkinTone: true),
    Emoji('ðŸ‘©â€ðŸ”§', 'Woman Mechanic', hasSkinTone: true),
    Emoji('ðŸ‘¨â€ðŸ­', 'Man Factory Worker', hasSkinTone: true),
    Emoji('ðŸ‘©â€ðŸ­', 'Woman Factory Worker', hasSkinTone: true),
    Emoji('ðŸ‘¨â€ðŸ’¼', 'Man Office Worker', hasSkinTone: true),
    Emoji('ðŸ‘©â€ðŸ’¼', 'Woman Office Worker', hasSkinTone: true),
    Emoji('ðŸ‘¨â€ðŸ”¬', 'Man Scientist', hasSkinTone: true),
    Emoji('ðŸ‘©â€ðŸ”¬', 'Woman Scientist', hasSkinTone: true),
    Emoji('ðŸ‘¨â€ðŸ’»', 'Man Technologist', hasSkinTone: true),
    Emoji('ðŸ‘©â€ðŸ’»', 'Woman Technologist', hasSkinTone: true),
    Emoji('ðŸ‘¨â€ðŸŽ¤', 'Man Singer', hasSkinTone: true),
    Emoji('ðŸ‘©â€ðŸŽ¤', 'Woman Singer', hasSkinTone: true),
    Emoji('ðŸ‘¨â€ðŸŽ¨', 'Man Artist', hasSkinTone: true),
    Emoji('ðŸ‘©â€ðŸŽ¨', 'Woman Artist', hasSkinTone: true),
    Emoji('ðŸ‘¨â€âœˆï¸', 'Man Pilot', hasSkinTone: true),
    Emoji('ðŸ‘©â€âœˆï¸', 'Woman Pilot', hasSkinTone: true),
    Emoji('ðŸ‘¨â€ðŸš€', 'Man Astronaut', hasSkinTone: true),
    Emoji('ðŸ‘©â€ðŸš€', 'Woman Astronaut', hasSkinTone: true),
    Emoji('ðŸ‘¨â€ðŸš’', 'Man Firefighter', hasSkinTone: true),
    Emoji('ðŸ‘©â€ðŸš’', 'Woman Firefighter', hasSkinTone: true),
    Emoji('ðŸ‘®â€â™‚ï¸', 'Man Police Officer', hasSkinTone: true),
    Emoji('ðŸ‘®â€â™€ï¸', 'Woman Police Officer', hasSkinTone: true),
    Emoji('ðŸ•µï¸â€â™‚ï¸', 'Man Detective', hasSkinTone: true),
    Emoji('ðŸ•µï¸â€â™€ï¸', 'Woman Detective', hasSkinTone: true),
    Emoji('ðŸ’‚â€â™‚ï¸', 'Man Guard', hasSkinTone: true),
    Emoji('ðŸ’‚â€â™€ï¸', 'Woman Guard', hasSkinTone: true),
    Emoji('ðŸ‘·â€â™‚ï¸', 'Man Construction Worker', hasSkinTone: true),
    Emoji('ðŸ‘·â€â™€ï¸', 'Woman Construction Worker', hasSkinTone: true),
    Emoji('ðŸ¤´', 'Prince', hasSkinTone: true),
    Emoji('ðŸ‘¸', 'Princess', hasSkinTone: true),
    Emoji('ðŸ‘³â€â™‚ï¸', 'Man Wearing Turban', hasSkinTone: true),
    Emoji('ðŸ‘³â€â™€ï¸', 'Woman Wearing Turban', hasSkinTone: true),
    Emoji('ðŸ‘²', 'Man With Chinese Cap', hasSkinTone: true),
    Emoji('ðŸ§•', 'Woman With Headscarf', hasSkinTone: true),
    Emoji('ðŸ¤µ', 'Man in Tuxedo', hasSkinTone: true),
    Emoji('ðŸ‘°', 'Bride With Veil', hasSkinTone: true),
    Emoji('ðŸ¤°', 'Pregnant Woman', hasSkinTone: true),
    Emoji('ðŸ¤±', 'Breast-Feeding', hasSkinTone: true),
    Emoji('ðŸ‘¼', 'Baby Angel', hasSkinTone: true),
    Emoji('ðŸŽ…', 'Santa Claus', hasSkinTone: true),
    Emoji('ðŸ¤¶', 'Mrs. Claus', hasSkinTone: true),
    Emoji('ðŸ¦¸â€â™‚ï¸', 'Man Superhero', hasSkinTone: true),
    Emoji('ðŸ¦¸â€â™€ï¸', 'Woman Superhero', hasSkinTone: true),
    Emoji('ðŸ¦¹â€â™‚ï¸', 'Man Supervillain', hasSkinTone: true),
    Emoji('ðŸ¦¹â€â™€ï¸', 'Woman Supervillain', hasSkinTone: true),
    Emoji('ðŸ§™â€â™‚ï¸', 'Man Mage', hasSkinTone: true),
    Emoji('ðŸ§™â€â™€ï¸', 'Woman Mage', hasSkinTone: true),
    Emoji('ðŸ§šâ€â™‚ï¸', 'Man Fairy', hasSkinTone: true),
    Emoji('ðŸ§šâ€â™€ï¸', 'Woman Fairy', hasSkinTone: true),
    Emoji('ðŸ§›â€â™‚ï¸', 'Man Vampire', hasSkinTone: true),
    Emoji('ðŸ§›â€â™€ï¸', 'Woman Vampire', hasSkinTone: true),
    Emoji('ðŸ§œâ€â™‚ï¸', 'Merman', hasSkinTone: true),
    Emoji('ðŸ§œâ€â™€ï¸', 'Mermaid', hasSkinTone: true),
    Emoji('ðŸ§â€â™‚ï¸', 'Man Elf', hasSkinTone: true),
    Emoji('ðŸ§â€â™€ï¸', 'Woman Elf', hasSkinTone: true),
    Emoji('ðŸ§žâ€â™‚ï¸', 'Man Genie'),
    Emoji('ðŸ§žâ€â™€ï¸', 'Woman Genie'),
    Emoji('ðŸ§Ÿâ€â™‚ï¸', 'Man Zombie'),
    Emoji('ðŸ§Ÿâ€â™€ï¸', 'Woman Zombie'),
    Emoji('ðŸ’†â€â™‚ï¸', 'Man Getting Massage', hasSkinTone: true),
    Emoji('ðŸ’†â€â™€ï¸', 'Woman Getting Massage', hasSkinTone: true),
    Emoji('ðŸ’‡â€â™‚ï¸', 'Man Getting Haircut', hasSkinTone: true),
    Emoji('ðŸ’‡â€â™€ï¸', 'Woman Getting Haircut', hasSkinTone: true),
    Emoji('ðŸš¶â€â™‚ï¸', 'Man Walking', hasSkinTone: true),
    Emoji('ðŸš¶â€â™€ï¸', 'Woman Walking', hasSkinTone: true),
    Emoji('ðŸƒâ€â™‚ï¸', 'Man Running', hasSkinTone: true),
    Emoji('ðŸƒâ€â™€ï¸', 'Woman Running', hasSkinTone: true),
    Emoji('ðŸ•º', 'Man Dancing', hasSkinTone: true),
    Emoji('ðŸ’ƒ', 'Woman Dancing', hasSkinTone: true),
    Emoji('ðŸ•´ï¸', 'Man in Suit Levitating', hasSkinTone: true),
    Emoji('ðŸ‘¯â€â™‚ï¸', 'Men With Bunny Ears'),
    Emoji('ðŸ‘¯â€â™€ï¸', 'Women With Bunny Ears'),
    Emoji('ðŸ§–â€â™‚ï¸', 'Man in Steamy Room', hasSkinTone: true),
    Emoji('ðŸ§–â€â™€ï¸', 'Woman in Steamy Room', hasSkinTone: true),
    Emoji('ðŸ§˜', 'Person in Lotus Position', hasSkinTone: true),
    Emoji('ðŸ‘­', 'Women Holding Hands', hasSkinTone: true),
    Emoji('ðŸ‘«', 'Woman and Man Holding Hands', hasSkinTone: true),
    Emoji('ðŸ‘¬', 'Men Holding Hands', hasSkinTone: true),
    Emoji('ðŸ’', 'Kiss'),
    Emoji('ðŸ‘¨â€â¤ï¸â€ðŸ’‹â€ðŸ‘¨', 'Kiss: Man, Man'),
    Emoji('ðŸ‘©â€â¤ï¸â€ðŸ’‹â€ðŸ‘©', 'Kiss: Woman, Woman'),
    Emoji('ðŸ’‘', 'Couple With Heart'),
    Emoji('ðŸ‘¨â€â¤ï¸â€ðŸ‘¨', 'Couple With Heart: Man, Man'),
    Emoji('ðŸ‘©â€â¤ï¸â€ðŸ‘©', 'Couple With Heart: Woman, Woman'),
    Emoji('ðŸ‘ª', 'Family'),
    Emoji('ðŸ‘¨â€ðŸ‘©â€ðŸ‘¦', 'Family: Man, Woman, Boy'),
    Emoji('ðŸ‘¨â€ðŸ‘©â€ðŸ‘§', 'Family: Man, Woman, Girl'),
    Emoji('ðŸ‘¨â€ðŸ‘©â€ðŸ‘§â€ðŸ‘¦', 'Family: Man, Woman, Girl, Boy'),
    Emoji('ðŸ‘¨â€ðŸ‘©â€ðŸ‘¦â€ðŸ‘¦', 'Family: Man, Woman, Boy, Boy'),
    Emoji('ðŸ‘¨â€ðŸ‘©â€ðŸ‘§â€ðŸ‘§', 'Family: Man, Woman, Girl, Girl'),
    Emoji('ðŸ‘¨â€ðŸ‘¨â€ðŸ‘¦', 'Family: Man, Man, Boy'),
    Emoji('ðŸ‘¨â€ðŸ‘¨â€ðŸ‘§', 'Family: Man, Man, Girl'),
    Emoji('ðŸ‘¨â€ðŸ‘¨â€ðŸ‘§â€ðŸ‘¦', 'Family: Man, Man, Girl, Boy'),
    Emoji('ðŸ‘¨â€ðŸ‘¨â€ðŸ‘¦â€ðŸ‘¦', 'Family: Man, Man, Boy, Boy'),
    Emoji('ðŸ‘¨â€ðŸ‘¨â€ðŸ‘§â€ðŸ‘§', 'Family: Man, Man, Girl, Girl'),
    Emoji('ðŸ‘©â€ðŸ‘©â€ðŸ‘¦', 'Family: Woman, Woman, Boy'),
    Emoji('ðŸ‘©â€ðŸ‘©â€ðŸ‘§', 'Family: Woman, Woman, Girl'),
    Emoji('ðŸ‘©â€ðŸ‘©â€ðŸ‘§â€ðŸ‘¦', 'Family: Woman, Woman, Girl, Boy'),
    Emoji('ðŸ‘©â€ðŸ‘©â€ðŸ‘¦â€ðŸ‘¦', 'Family: Woman, Woman, Boy, Boy'),
    Emoji('ðŸ‘©â€ðŸ‘©â€ðŸ‘§â€ðŸ‘§', 'Family: Woman, Woman, Girl, Girl'),
    Emoji('ðŸ‘¨â€ðŸ‘¦', 'Family: Man, Boy'),
    Emoji('ðŸ‘¨â€ðŸ‘¦â€ðŸ‘¦', 'Family: Man, Boy, Boy'),
    Emoji('ðŸ‘¨â€ðŸ‘§', 'Family: Man, Girl'),
    Emoji('ðŸ‘¨â€ðŸ‘§â€ðŸ‘¦', 'Family: Man, Girl, Boy'),
    Emoji('ðŸ‘¨â€ðŸ‘§â€ðŸ‘§', 'Family: Man, Girl, Girl'),
    Emoji('ðŸ‘©â€ðŸ‘¦', 'Family: Woman, Boy'),
    Emoji('ðŸ‘©â€ðŸ‘¦â€ðŸ‘¦', 'Family: Woman, Boy, Boy'),
    Emoji('ðŸ‘©â€ðŸ‘§', 'Family: Woman, Girl'),
    Emoji('ðŸ‘©â€ðŸ‘§â€ðŸ‘¦', 'Family: Woman, Girl, Boy'),
    Emoji('ðŸ‘©â€ðŸ‘§â€ðŸ‘§', 'Family: Woman, Girl, Girl'),
    Emoji('ðŸ—£ï¸', 'Speaking Head'),
    Emoji('ðŸ‘¤', 'Bust in Silhouette'),
    Emoji('ðŸ‘¥', 'Busts in Silhouette'),
    Emoji('ðŸ«‚', 'People Hugging'),
    Emoji('ðŸ‘£', 'Footprints'),
    Emoji('ðŸ§³', 'Luggage'),
    Emoji('ðŸŒ‚', 'Closed Umbrella'),
    Emoji('â˜‚ï¸', 'Umbrella'),
    Emoji('ðŸ§µ', 'Thread'),
    Emoji('ðŸ§¶', 'Yarn'),
    Emoji('ðŸ‘“', 'Glasses'),
    Emoji('ðŸ•¶ï¸', 'Sunglasses'),
    Emoji('ðŸ¥½', 'Goggles'),
    Emoji('ðŸ¥¼', 'Lab Coat'),
    Emoji('ðŸ‘”', 'Necktie'),
    Emoji('ðŸ‘•', 'T-Shirt'),
    Emoji('ðŸ‘–', 'Jeans'),
    Emoji('ðŸ§£', 'Scarf'),
    Emoji('ðŸ§¤', 'Gloves'),
    Emoji('ðŸ§¥', 'Coat'),
    Emoji('ðŸ§¦', 'Socks'),
    Emoji('ðŸ‘—', 'Dress'),
    Emoji('ðŸ‘˜', 'Kimono'),
    Emoji('ðŸ‘™', 'Bikini'),
    Emoji('ðŸ‘š', 'Womanâ€™s Clothes'),
    Emoji('ðŸ‘›', 'Purse'),
    Emoji('ðŸ‘œ', 'Handbag'),
    Emoji('ðŸ‘', 'Clutch Bag'),
    Emoji('ðŸŽ’', 'Backpack'),
    Emoji('ðŸ‘ž', 'Manâ€™s Shoe'),
    Emoji('ðŸ‘Ÿ', 'Running Shoe'),
    Emoji('ðŸ¥¾', 'Hiking Boot'),
    Emoji('ðŸ¥¿', 'Flat Shoe'),
    Emoji('ðŸ‘ ', 'High-Heeled Shoe'),
    Emoji('ðŸ‘¡', 'Womanâ€™s Sandal'),
    Emoji('ðŸ‘¢', 'Womanâ€™s Boot'),
    Emoji('ðŸ‘‘', 'Crown'),
    Emoji('ðŸ‘’', 'Womanâ€™s Hat'),
    Emoji('ðŸŽ©', 'Top Hat'),
    Emoji('ðŸŽ“', 'Graduation Cap'),
    Emoji('ðŸ§¢', 'Billed Cap'),
    Emoji('â›‘ï¸', 'Rescue Workerâ€™s Helmet'),
    Emoji('ðŸ’„', 'Lipstick'),
    Emoji('ðŸ’', 'Ring'),
    Emoji('ðŸ’¼', 'Briefcase')
  ]),

// ======================================================= Category.ANIMALS
  CategoryEmoji(Category.ANIMALS, [
    Emoji('ðŸ¶', 'Dog Face'),
    Emoji('ðŸ±', 'Cat Face'),
    Emoji('ðŸ­', 'Mouse Face'),
    Emoji('ðŸ¹', 'Hamster Face'),
    Emoji('ðŸ°', 'Rabbit Face'),
    Emoji('ðŸ¦Š', 'Fox Face'),
    Emoji('ðŸ»', 'Bear Face'),
    Emoji('ðŸ¼', 'Panda Face'),
    Emoji('ðŸ¨', 'Koala Face'),
    Emoji('ðŸ¯', 'Tiger Face'),
    Emoji('ðŸ¦', 'Lion Face'),
    Emoji('ðŸ®', 'Cow Face'),
    Emoji('ðŸ·', 'Pig Face'),
    Emoji('ðŸ½', 'Pig Nose'),
    Emoji('ðŸ¸', 'Frog Face'),
    Emoji('ðŸµ', 'Monkey Face'),
    Emoji('ðŸ™ˆ', 'See-No-Evil Monkey'),
    Emoji('ðŸ™‰', 'Hear-No-Evil Monkey'),
    Emoji('ðŸ™Š', 'Speak-No-Evil Monkey'),
    Emoji('ðŸ’', 'Monkey'),
    Emoji('ðŸ’¥', 'Collision'),
    Emoji('ðŸ’«', 'Dizzy'),
    Emoji('ðŸ’¦', 'Sweat Droplets'),
    Emoji('ðŸ’¨', 'Dashing Away'),
    Emoji('ðŸ¦', 'Gorilla'),
    Emoji('ðŸ•', 'Dog'),
    Emoji('ðŸ©', 'Poodle'),
    Emoji('ðŸº', 'Wolf Face'),
    Emoji('ðŸ¦', 'Raccoon'),
    Emoji('ðŸˆ', 'Cat'),
    Emoji('ðŸ…', 'Tiger'),
    Emoji('ðŸ†', 'Leopard'),
    Emoji('ðŸ´', 'Horse Face'),
    Emoji('ðŸŽ', 'Horse'),
    Emoji('ðŸ¦„', 'Unicorn Face'),
    Emoji('ðŸ¦“', 'Zebra'),
    Emoji('ðŸ‚', 'Ox'),
    Emoji('ðŸƒ', 'Water Buffalo'),
    Emoji('ðŸ„', 'Cow'),
    Emoji('ðŸ–', 'Pig'),
    Emoji('ðŸ—', 'Boar'),
    Emoji('ðŸ', 'Ram'),
    Emoji('ðŸ‘', 'Ewe'),
    Emoji('ðŸ', 'Goat'),
    Emoji('ðŸª', 'Camel'),
    Emoji('ðŸ«', 'Two-Hump Camel'),
    Emoji('ðŸ¦™', 'Llama'),
    Emoji('ðŸ¦’', 'Giraffe'),
    Emoji('ðŸ˜', 'Elephant'),
    Emoji('ðŸ¦', 'Rhinoceros'),
    Emoji('ðŸ¦›', 'Hippopotamus'),
    Emoji('ðŸ', 'Mouse'),
    Emoji('ðŸ€', 'Rat'),
    Emoji('ðŸ‡', 'Rabbit'),
    Emoji('ðŸ¿ï¸', 'Chipmunk'),
    Emoji('ðŸ¦”', 'Hedgehog'),
    Emoji('ðŸ¦‡', 'Bat'),
    Emoji('ðŸ¦˜', 'Kangaroo'),
    Emoji('ðŸ¦¡', 'Badger'),
    Emoji('ðŸ¾', 'Paw Prints'),
    Emoji('ðŸ¦ƒ', 'Turkey'),
    Emoji('ðŸ”', 'Chicken'),
    Emoji('ðŸ“', 'Rooster'),
    Emoji('ðŸ£', 'Hatching Chick'),
    Emoji('ðŸ¤', 'Baby Chick'),
    Emoji('ðŸ¥', 'Front-Facing Baby Chick'),
    Emoji('ðŸ¦', 'Bird'),
    Emoji('ðŸ§', 'Penguin'),
    Emoji('ðŸ•Šï¸', 'Dove'),
    Emoji('ðŸ¦…', 'Eagle'),
    Emoji('ðŸ¦†', 'Duck'),
    Emoji('ðŸ¦¢', 'Swan'),
    Emoji('ðŸ¦‰', 'Owl'),
    Emoji('ðŸ¦š', 'Peacock'),
    Emoji('ðŸ¦œ', 'Parrot'),
    Emoji('ðŸŠ', 'Crocodile'),
    Emoji('ðŸ¢', 'Turtle'),
    Emoji('ðŸ¦Ž', 'Lizard'),
    Emoji('ðŸ', 'Snake'),
    Emoji('ðŸ²', 'Dragon Face'),
    Emoji('ðŸ‰', 'Dragon'),
    Emoji('ðŸ¦•', 'Sauropod'),
    Emoji('ðŸ¦–', 'T-Rex'),
    Emoji('ðŸ§Œ', 'Troll'),
    Emoji('ðŸ³', 'Spouting Whale'),
    Emoji('ðŸ‹', 'Whale'),
    Emoji('ðŸ¬', 'Dolphin'),
    Emoji('ðŸŸ', 'Fish'),
    Emoji('ðŸ ', 'Tropical Fish'),
    Emoji('ðŸ¡', 'Blowfish'),
    Emoji('ðŸ¦ˆ', 'Shark'),
    Emoji('ðŸ™', 'Octopus'),
    Emoji('ðŸª¹', 'Empty Nest'),
    Emoji('ðŸªº', 'Nest with Eggs'),
    Emoji('ðŸš', 'Spiral Shell'),
    Emoji('ðŸª¸', 'Coral'),
    Emoji('ðŸŒ', 'Snail'),
    Emoji('ðŸ¦‹', 'Butterfly'),
    Emoji('ðŸ›', 'Bug'),
    Emoji('ðŸœ', 'Ant'),
    Emoji('ðŸ', 'Honeybee'),
    Emoji('ðŸž', 'Lady Beetle'),
    Emoji('ðŸ¦—', 'Cricket'),
    Emoji('ðŸ•·ï¸', 'Spider'),
    Emoji('ðŸ•¸ï¸', 'Spider Web'),
    Emoji('ðŸ¦‚', 'Scorpion'),
    Emoji('ðŸ¦Ÿ', 'Mosquito'),
    Emoji('ðŸ¦ ', 'Microbe'),
    Emoji('ðŸ’', 'Bouquet'),
    Emoji('ðŸŒ¸', 'Cherry Blossom'),
    Emoji('ðŸ’®', 'White Flower'),
    Emoji('ðŸµï¸', 'Rosette'),
    Emoji('ðŸª·', 'Lotus'),
    Emoji('ðŸŒ¹', 'Rose'),
    Emoji('ðŸ¥€', 'Wilted Flower'),
    Emoji('ðŸŒº', 'Hibiscus'),
    Emoji('ðŸŒ»', 'Sunflower'),
    Emoji('ðŸŒ¼', 'Blossom'),
    Emoji('ðŸŒ·', 'Tulip'),
    Emoji('ðŸŒ±', 'Seedling'),
    Emoji('ðŸŒ²', 'Evergreen Tree'),
    Emoji('ðŸŒ³', 'Deciduous Tree'),
    Emoji('ðŸŒ´', 'Palm Tree'),
    Emoji('ðŸŒµ', 'Cactus'),
    Emoji('ðŸŒ¾', 'Sheaf of Rice'),
    Emoji('ðŸŒ¿', 'Herb'),
    Emoji('â˜˜ï¸', 'Shamrock'),
    Emoji('ðŸ€', 'Four Leaf Clover'),
    Emoji('ðŸ', 'Maple Leaf'),
    Emoji('ðŸ‚', 'Fallen Leaf'),
    Emoji('ðŸƒ', 'Leaf Fluttering in Wind'),
    Emoji('ðŸ„', 'Mushroom'),
    Emoji('ðŸŒ°', 'Chestnut'),
    Emoji('ðŸ¦€', 'Crab'),
    Emoji('ðŸ¦ž', 'Lobster'),
    Emoji('ðŸ¦', 'Shrimp'),
    Emoji('ðŸ¦‘', 'Squid'),
    Emoji('ðŸŒ', 'Globe Showing Europe-Africa'),
    Emoji('ðŸŒŽ', 'Globe Showing Americas'),
    Emoji('ðŸŒ', 'Globe Showing Asia-Australia'),
    Emoji('ðŸŒ', 'Globe With Meridians'),
    Emoji('ðŸŒ‘', 'New Moon'),
    Emoji('ðŸŒ’', 'Waxing Crescent Moon'),
    Emoji('ðŸŒ“', 'First Quarter Moon'),
    Emoji('ðŸŒ”', 'Waxing Gibbous Moon'),
    Emoji('ðŸŒ•', 'Full Moon'),
    Emoji('ðŸŒ–', 'Waning Gibbous Moon'),
    Emoji('ðŸŒ—', 'Last Quarter Moon'),
    Emoji('ðŸŒ˜', 'Waning Crescent Moon'),
    Emoji('ðŸŒ™', 'Crescent Moon'),
    Emoji('ðŸŒš', 'New Moon Face'),
    Emoji('ðŸŒ›', 'First Quarter Moon Face'),
    Emoji('ðŸŒœ', 'Last Quarter Moon Face'),
    Emoji('â˜€ï¸', 'Sun'),
    Emoji('ðŸŒ', 'Full Moon Face'),
    Emoji('ðŸŒž', 'Sun With Face'),
    Emoji('â­', 'Star'),
    Emoji('ðŸŒŸ', 'Glowing Star'),
    Emoji('ðŸŒ ', 'Shooting Star'),
    Emoji('â˜ï¸', 'Cloud'),
    Emoji('â›…', 'Sun Behind Cloud'),
    Emoji('â›ˆï¸', 'Cloud With Lightning and Rain'),
    Emoji('ðŸŒ¤ï¸', 'Sun Behind Small Cloud'),
    Emoji('ðŸŒ¥ï¸', 'Sun Behind Large Cloud'),
    Emoji('ðŸŒ¦ï¸', 'Sun Behind Rain Cloud'),
    Emoji('ðŸŒ§ï¸', 'Cloud With Rain'),
    Emoji('ðŸŒ¨ï¸', 'Cloud With Snow'),
    Emoji('ðŸŒ©ï¸', 'Cloud With Lightning'),
    Emoji('ðŸŒªï¸', 'Tornado'),
    Emoji('ðŸŒ«ï¸', 'Fog'),
    Emoji('ðŸŒ¬ï¸', 'Wind Face'),
    Emoji('ðŸŒˆ', 'Rainbow'),
    Emoji('â˜‚ï¸', 'Umbrella'),
    Emoji('â˜”', 'Umbrella With Rain Drops'),
    Emoji('âš¡', 'High Voltage'),
    Emoji('â„ï¸', 'Snowflake'),
    Emoji('â˜ƒï¸', 'Snowman'),
    Emoji('â›„', 'Snowman Without Snow'),
    Emoji('â˜„ï¸', 'Comet'),
    Emoji('ðŸ”¥', 'Fire'),
    Emoji('ðŸ’§', 'Droplet'),
    Emoji('ðŸ«§', 'Bubbles'),
    Emoji('ðŸŒŠ', 'Water Wave'),
    Emoji('ðŸŽ„', 'Christmas Tree'),
    Emoji('âœ¨', 'Sparkles'),
    Emoji('ðŸŽ‹', 'Tanabata Tree'),
    Emoji('ðŸŽ', 'Pine Decoration')
  ]),

// ======================================================= Category.FOODS
  CategoryEmoji(Category.FOODS, [
    Emoji('ðŸ‡', 'Grapes'),
    Emoji('ðŸˆ', 'Melon'),
    Emoji('ðŸ‰', 'Watermelon'),
    Emoji('ðŸŠ', 'Tangerine'),
    Emoji('ðŸ‹', 'Lemon'),
    Emoji('ðŸŒ', 'Banana'),
    Emoji('ðŸ', 'Pineapple'),
    Emoji('ðŸ¥­', 'Mango'),
    Emoji('ðŸŽ', 'Red Apple'),
    Emoji('ðŸ', 'Green Apple'),
    Emoji('ðŸ', 'Pear'),
    Emoji('ðŸ‘', 'Peach'),
    Emoji('ðŸ’', 'Cherries'),
    Emoji('ðŸ“', 'Strawberry'),
    Emoji('ðŸ¥', 'Kiwi Fruit'),
    Emoji('ðŸ…', 'Tomato'),
    Emoji('ðŸ¥¥', 'Coconut'),
    Emoji('ðŸ¥‘', 'Avocado'),
    Emoji('ðŸ†', 'Eggplant'),
    Emoji('ðŸ¥”', 'Potato'),
    Emoji('ðŸ¥•', 'Carrot'),
    Emoji('ðŸŒ½', 'Ear of Corn'),
    Emoji('ðŸŒ¶ï¸', 'Hot Pepper'),
    Emoji('ðŸ¥’', 'Cucumber'),
    Emoji('ðŸ¥¬', 'Leafy Green'),
    Emoji('ðŸ¥¦', 'Broccoli'),
    Emoji('ðŸ„', 'Mushroom'),
    Emoji('ðŸ¥œ', 'Peanuts'),
    Emoji('ðŸ«˜', 'Beans'),
    Emoji('ðŸŒ°', 'Chestnut'),
    Emoji('ðŸž', 'Bread'),
    Emoji('ðŸ¥', 'Croissant'),
    Emoji('ðŸ¥–', 'Baguette Bread'),
    Emoji('ðŸ¥¨', 'Pretzel'),
    Emoji('ðŸ¥¯', 'Bagel'),
    Emoji('ðŸ¥ž', 'Pancakes'),
    Emoji('ðŸ§€', 'Cheese Wedge'),
    Emoji('ðŸ–', 'Meat on Bone'),
    Emoji('ðŸ—', 'Poultry Leg'),
    Emoji('ðŸ¥©', 'Cut of Meat'),
    Emoji('ðŸ¥“', 'Bacon'),
    Emoji('ðŸ”', 'Hamburger'),
    Emoji('ðŸŸ', 'French Fries'),
    Emoji('ðŸ•', 'Pizza'),
    Emoji('ðŸŒ­', 'Hot Dog'),
    Emoji('ðŸ¥ª', 'Sandwich'),
    Emoji('ðŸŒ®', 'Taco'),
    Emoji('ðŸŒ¯', 'Burrito'),
    Emoji('ðŸ¥™', 'Stuffed Flatbread'),
    Emoji('ðŸ³', 'Cooking'),
    Emoji('ðŸ¥˜', 'Shallow Pan of Food'),
    Emoji('ðŸ²', 'Pot of Food'),
    Emoji('ðŸ¥£', 'Bowl With Spoon'),
    Emoji('ðŸ¥—', 'Green Salad'),
    Emoji('ðŸ¿', 'Popcorn'),
    Emoji('ðŸ§‚', 'Salt'),
    Emoji('ðŸ¥«', 'Canned Food'),
    Emoji('ðŸ«™', 'Jar'),
    Emoji('ðŸ±', 'Bento Box'),
    Emoji('ðŸ˜', 'Rice Cracker'),
    Emoji('ðŸ™', 'Rice Ball'),
    Emoji('ðŸš', 'Cooked Rice'),
    Emoji('ðŸ›', 'Curry Rice'),
    Emoji('ðŸœ', 'Steaming Bowl'),
    Emoji('ðŸ', 'Spaghetti'),
    Emoji('ðŸ ', 'Roasted Sweet Potato'),
    Emoji('ðŸ¢', 'Oden'),
    Emoji('ðŸ£', 'Sushi'),
    Emoji('ðŸ¤', 'Fried Shrimp'),
    Emoji('ðŸ¥', 'Fish Cake With Swirl'),
    Emoji('ðŸ¥®', 'Moon Cake'),
    Emoji('ðŸ¡', 'Dango'),
    Emoji('ðŸ¥Ÿ', 'Dumpling'),
    Emoji('ðŸ¥ ', 'Fortune Cookie'),
    Emoji('ðŸ¥¡', 'Takeout Box'),
    Emoji('ðŸ¦', 'Soft Ice Cream'),
    Emoji('ðŸ§', 'Shaved Ice'),
    Emoji('ðŸ¨', 'Ice Cream'),
    Emoji('ðŸ©', 'Doughnut'),
    Emoji('ðŸª', 'Cookie'),
    Emoji('ðŸŽ‚', 'Birthday Cake'),
    Emoji('ðŸ°', 'Shortcake'),
    Emoji('ðŸ§', 'Cupcake'),
    Emoji('ðŸ¥§', 'Pie'),
    Emoji('ðŸ«', 'Chocolate Bar'),
    Emoji('ðŸ¬', 'Candy'),
    Emoji('ðŸ­', 'Lollipop'),
    Emoji('ðŸ®', 'Custard'),
    Emoji('ðŸ¯', 'Honey Pot'),
    Emoji('ðŸ¼', 'Baby Bottle'),
    Emoji('ðŸ¥›', 'Glass of Milk'),
    Emoji('ðŸ«—', 'Pouring Liquid'),
    Emoji('â˜•', 'Hot Beverage'),
    Emoji('ðŸµ', 'Teacup Without Handle'),
    Emoji('ðŸ§‰', 'Mate Drink'),
    Emoji('ðŸ¶', 'Sake'),
    Emoji('ðŸ¾', 'Bottle With Popping Cork'),
    Emoji('ðŸ·', 'Wine Glass'),
    Emoji('ðŸ¸', 'Cocktail Glass'),
    Emoji('ðŸ¹', 'Tropical Drink'),
    Emoji('ðŸº', 'Beer Mug'),
    Emoji('ðŸ»', 'Clinking Beer Mugs'),
    Emoji('ðŸ¥‚', 'Clinking Glasses'),
    Emoji('ðŸ¥ƒ', 'Tumbler Glass'),
    Emoji('ðŸ¥¤', 'Cup With Straw'),
    Emoji('ðŸ¥¢', 'Chopsticks'),
    Emoji('ðŸ½ï¸', 'Fork and Knife With Plate'),
    Emoji('ðŸ´', 'Fork and Knife'),
    Emoji('ðŸ¥„', 'Spoon')
  ]),

// ======================================================= Category.TRAVEL
  CategoryEmoji(Category.TRAVEL, [
    Emoji('ðŸ—¾', 'Map of Japan'),
    Emoji('ðŸ”ï¸', 'Snow-Capped Mountain'),
    Emoji('â›°ï¸', 'Mountain'),
    Emoji('ðŸŒ‹', 'Volcano'),
    Emoji('ðŸ—»', 'Mount Fuji'),
    Emoji('ðŸ•ï¸', 'Camping'),
    Emoji('ðŸ–ï¸', 'Beach With Umbrella'),
    Emoji('ðŸœï¸', 'Desert'),
    Emoji('ðŸï¸', 'Desert Island'),
    Emoji('ðŸžï¸', 'National Park'),
    Emoji('ðŸŸï¸', 'Stadium'),
    Emoji('ðŸ›ï¸', 'Classical Building'),
    Emoji('ðŸ—ï¸', 'Building Construction'),
    Emoji('ðŸ˜ï¸', 'Houses'),
    Emoji('ðŸšï¸', 'Derelict House'),
    Emoji('ðŸ ', 'House'),
    Emoji('ðŸ¡', 'House With Garden'),
    Emoji('ðŸ¢', 'Office Building'),
    Emoji('ðŸ£', 'Japanese Post Office'),
    Emoji('ðŸ¤', 'Post Office'),
    Emoji('ðŸ¥', 'Hospital'),
    Emoji('ðŸ¦', 'Bank'),
    Emoji('ðŸ¨', 'Hotel'),
    Emoji('ðŸ©', 'Love Hotel'),
    Emoji('ðŸª', 'Convenience Store'),
    Emoji('ðŸ«', 'School'),
    Emoji('ðŸ¬', 'Department Store'),
    Emoji('ðŸ­', 'Factory'),
    Emoji('ðŸ¯', 'Japanese Castle'),
    Emoji('ðŸ°', 'Castle'),
    Emoji('ðŸ’’', 'Wedding'),
    Emoji('ðŸ—¼', 'Tokyo Tower'),
    Emoji('ðŸ—½', 'Statue of Liberty'),
    Emoji('â›ª', 'Church'),
    Emoji('ðŸ•Œ', 'Mosque'),
    Emoji('ðŸ•', 'Synagogue'),
    Emoji('â›©ï¸', 'Shinto Shrine'),
    Emoji('ðŸ•‹', 'Kaaba'),
    Emoji('â›²', 'Fountain'),
    Emoji('â›º', 'Tent'),
    Emoji('ðŸŒ', 'Foggy'),
    Emoji('ðŸŒƒ', 'Night With Stars'),
    Emoji('ðŸ™ï¸', 'Cityscape'),
    Emoji('ðŸŒ„', 'Sunrise Over Mountains'),
    Emoji('ðŸŒ…', 'Sunrise'),
    Emoji('ðŸŒ†', 'Cityscape at Dusk'),
    Emoji('ðŸŒ‡', 'Sunset'),
    Emoji('ðŸŒ‰', 'Bridge at Night'),
    Emoji('ðŸŽ ', 'Carousel Horse'),
    Emoji('ðŸŽ¡', 'Ferris Wheel'),
    Emoji('ðŸŽ¢', 'Roller Coaster'),
    Emoji('ðŸš‚', 'Locomotive'),
    Emoji('ðŸšƒ', 'Railway Car'),
    Emoji('ðŸš„', 'High-Speed Train'),
    Emoji('ðŸš…', 'Bullet Train'),
    Emoji('ðŸš†', 'Train'),
    Emoji('ðŸš‡', 'Metro'),
    Emoji('ðŸšˆ', 'Light Rail'),
    Emoji('ðŸš‰', 'Station'),
    Emoji('ðŸšŠ', 'Tram'),
    Emoji('ðŸš', 'Monorail'),
    Emoji('ðŸšž', 'Mountain Railway'),
    Emoji('ðŸš‹', 'Tram Car'),
    Emoji('ðŸšŒ', 'Bus'),
    Emoji('ðŸš', 'Oncoming Bus'),
    Emoji('ðŸšŽ', 'Trolleybus'),
    Emoji('ðŸš', 'Minibus'),
    Emoji('ðŸš‘', 'Ambulance'),
    Emoji('ðŸš’', 'Fire Engine'),
    Emoji('ðŸš“', 'Police Car'),
    Emoji('ðŸš”', 'Oncoming Police Car'),
    Emoji('ðŸš•', 'Taxi'),
    Emoji('ðŸš–', 'Oncoming Taxi'),
    Emoji('ðŸš—', 'Automobile'),
    Emoji('ðŸš˜', 'Oncoming Automobile'),
    Emoji('ðŸšš', 'Delivery Truck'),
    Emoji('ðŸš›', 'Articulated Lorry'),
    Emoji('ðŸšœ', 'Tractor'),
    Emoji('ðŸŽï¸', 'Racing Car'),
    Emoji('ðŸï¸', 'Motorcycle'),
    Emoji('ðŸ›µ', 'Motor Scooter'),
    Emoji('ðŸš²', 'Bicycle'),
    Emoji('ðŸ›´', 'Kick Scooter'),
    Emoji('ðŸš', 'Bus Stop'),
    Emoji('ðŸ›¤ï¸', 'Railway Track'),
    Emoji('â›½', 'Fuel Pump'),
    Emoji('ðŸ›ž', 'Wheel'),
    Emoji('ðŸš¨', 'Police Car Light'),
    Emoji('ðŸš¥', 'Horizontal Traffic Light'),
    Emoji('ðŸš¦', 'Vertical Traffic Light'),
    Emoji('ðŸš§', 'Construction'),
    Emoji('âš“', 'Anchor'),
    Emoji('â›µ', 'Sailboat'),
    Emoji('ðŸš¤', 'Speedboat'),
    Emoji('ðŸ›³ï¸', 'Passenger Ship'),
    Emoji('â›´ï¸', 'Ferry'),
    Emoji('ðŸ›¥ï¸', 'Motor Boat'),
    Emoji('ðŸš¢', 'Ship'),
    Emoji('ðŸ›Ÿ', 'Ring Buoy'),
    Emoji('âœˆï¸', 'Airplane'),
    Emoji('ðŸ›©ï¸', 'Small Airplane'),
    Emoji('ðŸ›«', 'Airplane Departure'),
    Emoji('ðŸ›¬', 'Airplane Arrival'),
    Emoji('ðŸ’º', 'Seat'),
    Emoji('ðŸš', 'Helicopter'),
    Emoji('ðŸšŸ', 'Suspension Railway'),
    Emoji('ðŸš ', 'Mountain Cableway'),
    Emoji('ðŸš¡', 'Aerial Tramway'),
    Emoji('ðŸ›°ï¸', 'Satellite'),
    Emoji('ðŸš€', 'Rocket'),
    Emoji('ðŸ›¸', 'Flying Saucer'),
    Emoji('ðŸŒ ', 'Shooting Star'),
    Emoji('ðŸŒŒ', 'Milky Way'),
    Emoji('â›±ï¸', 'Umbrella on Ground'),
    Emoji('ðŸŽ†', 'Fireworks'),
    Emoji('ðŸŽ‡', 'Sparkler'),
    Emoji('ðŸŽ‘', 'Moon Viewing Ceremony'),
    Emoji('ðŸ—¿', 'Moai'),
    Emoji('ðŸ›‚', 'Passport Control'),
    Emoji('ðŸ›ƒ', 'Customs'),
    Emoji('ðŸ›„', 'Baggage Claim'),
    Emoji('ðŸ›…', 'Left Luggage')
  ]),

// ======================================================= Category.ACTIVITIES
  CategoryEmoji(Category.ACTIVITIES, [
    Emoji('ðŸ§—â€â™‚ï¸', 'Man Climbing', hasSkinTone: true),
    Emoji('ðŸ§—â€â™€ï¸', 'Woman Climbing', hasSkinTone: true),
    Emoji('ðŸ‡', 'Horse Racing', hasSkinTone: true),
    Emoji('â›·ï¸', 'Skier'),
    Emoji('ðŸ‚', 'Snowboarder'),
    Emoji('ðŸŒï¸â€â™‚ï¸', 'Man Golfing', hasSkinTone: true),
    Emoji('ðŸŒï¸â€â™€ï¸', 'Woman Golfing', hasSkinTone: true),
    Emoji('ðŸ„â€â™‚ï¸', 'Man Surfing', hasSkinTone: true),
    Emoji('ðŸ„â€â™€ï¸', 'Woman Surfing', hasSkinTone: true),
    Emoji('ðŸš£â€â™‚ï¸', 'Man Rowing Boat', hasSkinTone: true),
    Emoji('ðŸš£â€â™€ï¸', 'Woman Rowing Boat', hasSkinTone: true),
    Emoji('ðŸŠâ€â™‚ï¸', 'Man Swimming', hasSkinTone: true),
    Emoji('ðŸŠâ€â™€ï¸', 'Woman Swimming', hasSkinTone: true),
    Emoji('â›¹ï¸â€â™‚ï¸', 'Man Bouncing Ball', hasSkinTone: true),
    Emoji('â›¹ï¸â€â™€ï¸', 'Woman Bouncing Ball', hasSkinTone: true),
    Emoji('ðŸ‹ï¸â€â™‚ï¸', 'Man Lifting Weights', hasSkinTone: true),
    Emoji('ðŸ‹ï¸â€â™€ï¸', 'Woman Lifting Weights', hasSkinTone: true),
    Emoji('ðŸš´â€â™‚ï¸', 'Man Biking', hasSkinTone: true),
    Emoji('ðŸš´â€â™€ï¸', 'Woman Biking', hasSkinTone: true),
    Emoji('ðŸšµâ€â™‚ï¸', 'Man Mountain Biking', hasSkinTone: true),
    Emoji('ðŸšµâ€â™€ï¸', 'Woman Mountain Biking', hasSkinTone: true),
    Emoji('ðŸ¤¸â€â™‚ï¸', 'Man Cartwheeling', hasSkinTone: true),
    Emoji('ðŸ¤¸â€â™€ï¸', 'Woman Cartwheeling', hasSkinTone: true),
    Emoji('ðŸ¤¼â€â™‚ï¸', 'Men Wrestling', hasSkinTone: true),
    Emoji('ðŸ¤¼â€â™€ï¸', 'Women Wrestling', hasSkinTone: true),
    Emoji('ðŸ¤½â€â™‚ï¸', 'Man Playing Water Polo', hasSkinTone: true),
    Emoji('ðŸ¤½â€â™€ï¸', 'Woman Playing Water Polo', hasSkinTone: true),
    Emoji('ðŸ¤¾â€â™‚ï¸', 'Man Playing Handball', hasSkinTone: true),
    Emoji('ðŸ¤¾â€â™€ï¸', 'Woman Playing Handball', hasSkinTone: true),
    Emoji('ðŸ¤¹â€â™‚ï¸', 'Man Juggling', hasSkinTone: true),
    Emoji('ðŸ¤¹â€â™€ï¸', 'Woman Juggling', hasSkinTone: true),
    Emoji('ðŸ§˜â€â™‚ï¸', 'Man in Lotus Position', hasSkinTone: true),
    Emoji('ðŸ§˜â€â™€ï¸', 'Woman in Lotus Position', hasSkinTone: true),
    Emoji('ðŸŽª', 'Circus Tent'),
    Emoji('ðŸ›¹', 'Skateboard'),
    Emoji('ðŸŽ—ï¸', 'Reminder Ribbon'),
    Emoji('ðŸŽŸï¸', 'Admission Tickets'),
    Emoji('ðŸŽ«', 'Ticket'),
    Emoji('ðŸŽ–ï¸', 'Military Medal'),
    Emoji('ðŸ†', 'Trophy'),
    Emoji('ðŸ…', 'Sports Medal'),
    Emoji('ðŸ¥‡', '1st Place Medal'),
    Emoji('ðŸ¥ˆ', '2nd Place Medal'),
    Emoji('ðŸ¥‰', '3rd Place Medal'),
    Emoji('âš½', 'Soccer Ball'),
    Emoji('âš¾', 'Baseball'),
    Emoji('ðŸ¥Ž', 'Softball'),
    Emoji('ðŸ€', 'Basketball'),
    Emoji('ðŸ', 'Volleyball'),
    Emoji('ðŸˆ', 'American Football'),
    Emoji('ðŸ‰', 'Rugby Football'),
    Emoji('ðŸŽ¾', 'Tennis'),
    Emoji('ðŸ¥', 'Flying Disc'),
    Emoji('ðŸŽ³', 'Bowling'),
    Emoji('ðŸ', 'Cricket Game'),
    Emoji('ðŸ‘', 'Field Hockey'),
    Emoji('ðŸ’', 'Ice Hockey'),
    Emoji('ðŸ¥', 'Lacrosse'),
    Emoji('ðŸ“', 'Ping Pong'),
    Emoji('ðŸ¸', 'Badminton'),
    Emoji('ðŸªƒ', 'Boomerang'),
    Emoji('ðŸ¥…', 'Goal Net'),
    Emoji('â›³', 'Flag in Hole'),
    Emoji('ðŸª', 'Kite'),
    Emoji('ðŸ›', 'Playground Slide'),
    Emoji('ðŸ¹', 'Bow and Arrow'),
    Emoji('ðŸŽ£', 'Fishing Pole'),
    Emoji('ðŸ¤¿ ', 'Diving Mask'),
    Emoji('ðŸ¥Š', 'Boxing Glove'),
    Emoji('ðŸ¥‹', 'Martial Arts Uniform'),
    Emoji('ðŸŽ½', 'Running Shirt'),
    Emoji('ðŸ›¼', 'Roller Skate'),
    Emoji('ðŸ›·', 'Sled'),
    Emoji('â›¸ï¸', 'Ice Skate'),
    Emoji('ðŸ¥Œ', 'Curling Stone'),
    Emoji('ðŸŽ¿', 'Skis'),
    Emoji('ðŸŽ¯', 'Direct Hit'),
    Emoji('ðŸŽ±', 'Pool 8 Ball'),
    Emoji('ðŸŽ®', 'Video Game'),
    Emoji('ðŸŽ°', 'Slot Machine'),
    Emoji('ðŸŽ²', 'Game Die'),
    Emoji('ðŸ§©', 'Jigsaw'),
    Emoji('â™Ÿï¸', 'Chess Pawn'),
    Emoji('ðŸŽ­', 'Performing Arts'),
    Emoji('ðŸŽ¨', 'Artist Palette'),
    Emoji('ðŸ§µ', 'Thread'),
    Emoji('ðŸ§¶', 'Yarn'),
    Emoji('ðŸŽ¼', 'Musical Score'),
    Emoji('ðŸŽ¤', 'Microphone'),
    Emoji('ðŸŽ§', 'Headphone'),
    Emoji('ðŸŽ·', 'Saxophone'),
    Emoji('ðŸŽ¸', 'Guitar'),
    Emoji('ðŸŽ¹', 'Musical Keyboard'),
    Emoji('ðŸŽº', 'Trumpet'),
    Emoji('ðŸŽ»', 'Violin'),
    Emoji('ðŸ¥', 'Drum'),
    Emoji('ðŸŽ¬', 'Clapper Board')
  ]),

// ======================================================= Category.OBJECTS
  CategoryEmoji(Category.OBJECTS, [
    Emoji('ðŸ’Œ', 'Love Letter'),
    Emoji('ðŸ•³ï¸', 'Hole'),
    Emoji('ðŸ’£', 'Bomb'),
    Emoji('ðŸ›€', 'Person Taking Bath'),
    Emoji('ðŸ›Œ', 'Person in Bed'),
    Emoji('ðŸº', 'Amphora'),
    Emoji('ðŸ—ºï¸', 'World Map'),
    Emoji('ðŸ§­', 'Compass'),
    Emoji('ðŸ§±', 'Brick'),
    Emoji('ðŸ’ˆ', 'Barber Pole'),
    Emoji('ðŸ›¢ï¸', 'Oil Drum'),
    Emoji('ðŸ›Žï¸', 'Bellhop Bell'),
    Emoji('ðŸ§³', 'Luggage'),
    Emoji('âŒ›', 'Hourglass Done'),
    Emoji('â³', 'Hourglass Not Done'),
    Emoji('âŒš', 'Watch'),
    Emoji('â°', 'Alarm Clock'),
    Emoji('â±ï¸', 'Stopwatch'),
    Emoji('â²ï¸', 'Timer Clock'),
    Emoji('ðŸ•°ï¸', 'Mantelpiece Clock'),
    Emoji('ðŸŒ¡ï¸', 'Thermometer'),
    Emoji('â›±ï¸', 'Umbrella on Ground'),
    Emoji('ðŸ§¨', 'Firecracker'),
    Emoji('ðŸŽˆ', 'Balloon'),
    Emoji('ðŸŽ‰', 'Party Popper'),
    Emoji('ðŸŽŠ', 'Confetti Ball'),
    Emoji('ðŸŽŽ', 'Japanese Dolls'),
    Emoji('ðŸŽ', 'Carp Streamer'),
    Emoji('ðŸŽ', 'Wind Chime'),
    Emoji('ðŸª©', 'Mirror Ball'),
    Emoji('ðŸ§§', 'Red Envelope'),
    Emoji('ðŸŽ€', 'Ribbon'),
    Emoji('ðŸŽ', 'Wrapped Gift'),
    Emoji('ðŸ”®', 'Crystal Ball'),
    Emoji('ðŸ§¿', 'Nazar Amulet'),
    Emoji('ðŸª¬', 'Hamsa'),
    Emoji('ðŸ•¹ï¸', 'Joystick'),
    Emoji('ðŸ§¸', 'Teddy Bear'),
    Emoji('ðŸ–¼ï¸', 'Framed Picture'),
    Emoji('ðŸ§µ', 'Thread'),
    Emoji('ðŸ§¶', 'Yarn'),
    Emoji('ðŸ›ï¸', 'Shopping Bags'),
    Emoji('ðŸ“¿', 'Prayer Beads'),
    Emoji('ðŸ’Ž', 'Gem Stone'),
    Emoji('ðŸ“¯', 'Postal Horn'),
    Emoji('ðŸŽ™ï¸', 'Studio Microphone'),
    Emoji('ðŸŽšï¸', 'Level Slider'),
    Emoji('ðŸŽ›ï¸', 'Control Knobs'),
    Emoji('ðŸ“»', 'Radio'),
    Emoji('ðŸ“±', 'Mobile Phone'),
    Emoji('ðŸ“²', 'Mobile Phone With Arrow'),
    Emoji('â˜Žï¸', 'Telephone'),
    Emoji('ðŸ“ž', 'Telephone Receiver'),
    Emoji('ðŸ“Ÿ', 'Pager'),
    Emoji('ðŸ“ ', 'Fax Machine'),
    Emoji('ðŸ”‹', 'Battery'),
    Emoji('ðŸª«', 'Low Battery'),
    Emoji('ðŸ”Œ', 'Electric Plug'),
    Emoji('ðŸ’»', 'Laptop Computer'),
    Emoji('ðŸ–¥ï¸', 'Desktop Computer'),
    Emoji('ðŸ–¨ï¸', 'Printer'),
    Emoji('âŒ¨ï¸', 'Keyboard'),
    Emoji('ðŸ–±ï¸', 'Computer Mouse'),
    Emoji('ðŸ–²ï¸', 'Trackball'),
    Emoji('ðŸ’½', 'Computer Disk'),
    Emoji('ðŸ’¾', 'Floppy Disk'),
    Emoji('ðŸ’¿', 'Optical Disk'),
    Emoji('ðŸ“€', 'DVD'),
    Emoji('ðŸ§®', 'Abacus'),
    Emoji('ðŸŽ¥', 'Movie Camera'),
    Emoji('ðŸŽžï¸', 'Film Frames'),
    Emoji('ðŸ“½ï¸', 'Film Projector'),
    Emoji('ðŸ“º', 'Television'),
    Emoji('ðŸ“·', 'Camera'),
    Emoji('ðŸ“¸', 'Camera With Flash'),
    Emoji('ðŸ“¹', 'Video Camera'),
    Emoji('ðŸ“¼', 'Videocassette'),
    Emoji('ðŸ”', 'Magnifying Glass Tilted Left'),
    Emoji('ðŸ”Ž', 'Magnifying Glass Tilted Right'),
    Emoji('ðŸ•¯ï¸', 'Candle'),
    Emoji('ðŸ’¡', 'Light Bulb'),
    Emoji('ðŸ”¦', 'Flashlight'),
    Emoji('ðŸ®', 'Red Paper Lantern'),
    Emoji('ðŸ“”', 'Notebook With Decorative Cover'),
    Emoji('ðŸ“•', 'Closed Book'),
    Emoji('ðŸ“–', 'Open Book'),
    Emoji('ðŸ“—', 'Green Book'),
    Emoji('ðŸ“˜', 'Blue Book'),
    Emoji('ðŸ“™', 'Orange Book'),
    Emoji('ðŸ“š', 'Books'),
    Emoji('ðŸ““', 'Notebook'),
    Emoji('ðŸ“ƒ', 'Page With Curl'),
    Emoji('ðŸ“œ', 'Scroll'),
    Emoji('ðŸ“„', 'Page Facing Up'),
    Emoji('ðŸ“°', 'Newspaper'),
    Emoji('ðŸ—žï¸', 'Rolled-Up Newspaper'),
    Emoji('ðŸ“‘', 'Bookmark Tabs'),
    Emoji('ðŸ”–', 'Bookmark'),
    Emoji('ðŸ·ï¸', 'Label'),
    Emoji('ðŸ’°', 'Money Bag'),
    Emoji('ðŸ’´', 'Yen Banknote'),
    Emoji('ðŸ’µ', 'Dollar Banknote'),
    Emoji('ðŸ’¶', 'Euro Banknote'),
    Emoji('ðŸ’·', 'Pound Banknote'),
    Emoji('ðŸ’¸', 'Money With Wings'),
    Emoji('ðŸ’³', 'Credit Card'),
    Emoji('ðŸªª', 'Identification Card'),
    Emoji('ðŸ§¾', 'Receipt'),
    Emoji('âœ‰ï¸', 'Envelope'),
    Emoji('ðŸ“§', 'E-Mail'),
    Emoji('ðŸ“¨', 'Incoming Envelope'),
    Emoji('ðŸ“©', 'Envelope With Arrow'),
    Emoji('ðŸ“¤', 'Outbox Tray'),
    Emoji('ðŸ“¥', 'Inbox Tray'),
    Emoji('ðŸ“¦', 'Package'),
    Emoji('ðŸ“«', 'Closed Mailbox With Raised Flag'),
    Emoji('ðŸ“ª', 'Closed Mailbox With Lowered Flag'),
    Emoji('ðŸ“¬', 'Open Mailbox With Raised Flag'),
    Emoji('ðŸ“­', 'Open Mailbox With Lowered Flag'),
    Emoji('ðŸ“®', 'Postbox'),
    Emoji('ðŸ—³ï¸', 'Ballot Box With Ballot'),
    Emoji('âœï¸', 'Pencil'),
    Emoji('âœ’ï¸', 'Black Nib'),
    Emoji('ðŸ–‹ï¸', 'Fountain Pen'),
    Emoji('ðŸ–Šï¸', 'Pen'),
    Emoji('ðŸ–Œï¸', 'Paintbrush'),
    Emoji('ðŸ–ï¸', 'Crayon'),
    Emoji('ðŸ“', 'Memo'),
    Emoji('ðŸ“', 'File Folder'),
    Emoji('ðŸ“‚', 'Open File Folder'),
    Emoji('ðŸ—‚ï¸', 'Card Index Dividers'),
    Emoji('ðŸ“…', 'Calendar'),
    Emoji('ðŸ“†', 'Tear-Off Calendar'),
    Emoji('ðŸ—’ï¸', 'Spiral Notepad'),
    Emoji('ðŸ—“ï¸', 'Spiral Calendar'),
    Emoji('ðŸ“‡', 'Card Index'),
    Emoji('ðŸ“ˆ', 'Chart Increasing'),
    Emoji('ðŸ“‰', 'Chart Decreasing'),
    Emoji('ðŸ“Š', 'Bar Chart'),
    Emoji('ðŸ“‹', 'Clipboard'),
    Emoji('ðŸ“Œ', 'Pushpin'),
    Emoji('ðŸ“', 'Round Pushpin'),
    Emoji('ðŸ“Ž', 'Paperclip'),
    Emoji('ðŸ–‡ï¸', 'Linked Paperclips'),
    Emoji('ðŸ“', 'Straight Ruler'),
    Emoji('ðŸ“', 'Triangular Ruler'),
    Emoji('âœ‚ï¸', 'Scissors'),
    Emoji('ðŸ—ƒï¸', 'Card File Box'),
    Emoji('ðŸ—„ï¸', 'File Cabinet'),
    Emoji('ðŸ—‘ï¸', 'Wastebasket'),
    Emoji('ðŸ”’', 'Locked'),
    Emoji('ðŸ”“', 'Unlocked'),
    Emoji('ðŸ”', 'Locked With Pen'),
    Emoji('ðŸ”', 'Locked With Key'),
    Emoji('ðŸ”‘', 'Key'),
    Emoji('ðŸ—ï¸', 'Old Key'),
    Emoji('ðŸ”¨', 'Hammer'),
    Emoji('â›ï¸', 'Pick'),
    Emoji('âš’ï¸', 'Hammer and Pick'),
    Emoji('ðŸ› ï¸', 'Hammer and Wrench'),
    Emoji('ðŸ”ª', 'Kitchen Knife'),
    Emoji('ðŸ—¡ï¸', 'Dagger'),
    Emoji('âš”ï¸', 'Crossed Swords'),
    Emoji('ðŸ”«', 'Pistol'),
    Emoji('ðŸ›¡ï¸', 'Shield'),
    Emoji('ðŸ”§', 'Wrench'),
    Emoji('ðŸ”©', 'Nut and Bolt'),
    Emoji('âš™ï¸', 'Gear'),
    Emoji('ðŸ—œï¸', 'Clamp'),
    Emoji('âš–ï¸', 'Balance Scale'),
    Emoji('ðŸ”—', 'Link'),
    Emoji('â›“ï¸', 'Chains'),
    Emoji('ðŸ§°', 'Toolbox'),
    Emoji('ðŸ§²', 'Magnet'),
    Emoji('âš—ï¸', 'Alembic'),
    Emoji('ðŸ§ª', 'Test Tube'),
    Emoji('ðŸ§«', 'Petri Dish'),
    Emoji('ðŸ§¬', 'DNA'),
    Emoji('ðŸ”¬', 'Microscope'),
    Emoji('ðŸ©»', 'X-Ray'),
    Emoji('ðŸ”­', 'Telescope'),
    Emoji('ðŸ“¡', 'Satellite Antenna'),
    Emoji('ðŸ’‰', 'Syringe'),
    Emoji('ðŸ’Š', 'Pill'),
    Emoji('ðŸšª', 'Door'),
    Emoji('ðŸ›ï¸', 'Bed'),
    Emoji('ðŸ›‹ï¸', 'Couch and Lamp'),
    Emoji('ðŸš½', 'Toilet'),
    Emoji('ðŸš¿', 'Shower'),
    Emoji('ðŸ›', 'Bathtub'),
    Emoji('ðŸ§´', 'Lotion Bottle'),
    Emoji('ðŸ§·', 'Safety Pin'),
    Emoji('ðŸ§¹', 'Broom'),
    Emoji('ðŸ§º', 'Basket'),
    Emoji('ðŸ§»', 'Roll of Paper'),
    Emoji('ðŸ§¼', 'Soap'),
    Emoji('ðŸ§½', 'Sponge'),
    Emoji('ðŸ§¯', 'Fire Extinguisher'),
    Emoji('ðŸš¬', 'Cigarette'),
    Emoji('âš°ï¸', 'Coffin'),
    Emoji('âš±ï¸', 'Funeral Urn'),
    Emoji('ðŸš°', 'Potable Water')
  ]),

// ======================================================= Category.SYMBOLS
  CategoryEmoji(Category.SYMBOLS, [
    Emoji('ðŸ’˜', 'Heart With Arrow'),
    Emoji('ðŸ’', 'Heart With Ribbon'),
    Emoji('ðŸ’–', 'Sparkling Heart'),
    Emoji('ðŸ’—', 'Growing Heart'),
    Emoji('ðŸ’“', 'Beating Heart'),
    Emoji('ðŸ’ž', 'Revolving Hearts'),
    Emoji('ðŸ’•', 'Two Hearts'),
    Emoji('ðŸ’Ÿ', 'Heart Decoration'),
    Emoji('â£ï¸', 'Heavy Heart Exclamation'),
    Emoji('ðŸ’”', 'Broken Heart'),
    Emoji('â¤ï¸â€ðŸ”¥', 'Heart on Fire'),
    Emoji('â¤ï¸', 'Red Heart'),
    Emoji('ðŸ§¡', 'Orange Heart'),
    Emoji('ðŸ’›', 'Yellow Heart'),
    Emoji('ðŸ’š', 'Green Heart'),
    Emoji('ðŸ’™', 'Blue Heart'),
    Emoji('ðŸ’œ', 'Purple Heart'),
    Emoji('ðŸ–¤', 'Black Heart'),
    Emoji('ðŸ’¯', 'Hundred Points'),
    Emoji('ðŸ’¢', 'Anger Symbol'),
    Emoji('ðŸ’¬', 'Speech Balloon'),
    Emoji('ðŸ‘ï¸â€ðŸ—¨ï¸', 'Eye in Speech Bubble'),
    Emoji('ðŸ—¯ï¸', 'Right Anger Bubble'),
    Emoji('ðŸ’­', 'Thought Balloon'),
    Emoji('ðŸ’¤', 'Zzz'),
    Emoji('ðŸ’®', 'White Flower'),
    Emoji('â™¨ï¸', 'Hot Springs'),
    Emoji('ðŸ’ˆ', 'Barber Pole'),
    Emoji('ðŸ›‘', 'Stop Sign'),
    Emoji('ðŸ•›', 'Twelve Oâ€™Clock'),
    Emoji('ðŸ•§', 'Twelve-Thirty'),
    Emoji('ðŸ•', 'One Oâ€™Clock'),
    Emoji('ðŸ•œ', 'One-Thirty'),
    Emoji('ðŸ•‘', 'Two Oâ€™Clock'),
    Emoji('ðŸ•', 'Two-Thirty'),
    Emoji('ðŸ•’', 'Three Oâ€™Clock'),
    Emoji('ðŸ•ž', 'Three-Thirty'),
    Emoji('ðŸ•“', 'Four Oâ€™Clock'),
    Emoji('ðŸ•Ÿ', 'Four-Thirty'),
    Emoji('ðŸ•”', 'Five Oâ€™Clock'),
    Emoji('ðŸ• ', 'Five-Thirty'),
    Emoji('ðŸ••', 'Six Oâ€™Clock'),
    Emoji('ðŸ•¡', 'Six-Thirty'),
    Emoji('ðŸ•–', 'Seven Oâ€™Clock'),
    Emoji('ðŸ•¢', 'Seven-Thirty'),
    Emoji('ðŸ•—', 'Eight Oâ€™Clock'),
    Emoji('ðŸ•£', 'Eight-Thirty'),
    Emoji('ðŸ•˜', 'Nine Oâ€™Clock'),
    Emoji('ðŸ•¤', 'Nine-Thirty'),
    Emoji('ðŸ•™', 'Ten Oâ€™Clock'),
    Emoji('ðŸ•¥', 'Ten-Thirty'),
    Emoji('ðŸ•š', 'Eleven Oâ€™Clock'),
    Emoji('ðŸ•¦', 'Eleven-Thirty'),
    Emoji('ðŸŒ€', 'Cyclone'),
    Emoji('â™ ï¸', 'Spade Suit'),
    Emoji('â™¥ï¸', 'Heart Suit'),
    Emoji('â™¦ï¸', 'Diamond Suit'),
    Emoji('â™£ï¸', 'Club Suit'),
    Emoji('ðŸƒ', 'Joker'),
    Emoji('ðŸ€„', 'Mahjong Red Dragon'),
    Emoji('ðŸŽ´', 'Flower Playing Cards'),
    Emoji('ðŸ”‡', 'Muted Speaker'),
    Emoji('ðŸ”ˆ', 'Speaker Low Volume'),
    Emoji('ðŸ”‰', 'Speaker Medium Volume'),
    Emoji('ðŸ”Š', 'Speaker High Volume'),
    Emoji('ðŸ“¢', 'Loudspeaker'),
    Emoji('ðŸ“£', 'Megaphone'),
    Emoji('ðŸ“¯', 'Postal Horn'),
    Emoji('ðŸ””', 'Bell'),
    Emoji('ðŸ”•', 'Bell With Slash'),
    Emoji('ðŸŽµ', 'Musical Note'),
    Emoji('ðŸŽ¶', 'Musical Notes'),
    Emoji('ðŸ§', 'ATM Sign'),
    Emoji('ðŸš®', 'Litter in Bin Sign'),
    Emoji('ðŸš°', 'Potable Water'),
    Emoji('â™¿', 'Wheelchair Symbol'),
    Emoji('ðŸ©¼', 'Crutch'),
    Emoji('ðŸš¹', 'Menâ€™s Room'),
    Emoji('ðŸšº', 'Womenâ€™s Room'),
    Emoji('ðŸš»', 'Restroom'),
    Emoji('ðŸš¼', 'Baby Symbol'),
    Emoji('ðŸš¾', 'Water Closet'),
    Emoji('âš ï¸', 'Warning'),
    Emoji('ðŸš¸', 'Children Crossing'),
    Emoji('â›”', 'No Entry'),
    Emoji('ðŸš«', 'Prohibited'),
    Emoji('ðŸš³', 'No Bicycles'),
    Emoji('ðŸš­', 'No Smoking'),
    Emoji('ðŸš¯', 'No Littering'),
    Emoji('ðŸš±', 'Non-Potable Water'),
    Emoji('ðŸš·', 'No Pedestrians'),
    Emoji('ðŸ”ž', 'No One Under Eighteen'),
    Emoji('â˜¢ï¸', 'Radioactive'),
    Emoji('â˜£ï¸', 'Biohazard'),
    Emoji('â¬†ï¸', 'Up Arrow'),
    Emoji('â†—ï¸', 'Up-Right Arrow'),
    Emoji('âž¡ï¸', 'Right Arrow'),
    Emoji('â†˜ï¸', 'Down-Right Arrow'),
    Emoji('â¬‡ï¸', 'Down Arrow'),
    Emoji('â†™ï¸', 'Down-Left Arrow'),
    Emoji('â¬…ï¸', 'Left Arrow'),
    Emoji('â†–ï¸', 'Up-Left Arrow'),
    Emoji('â†•ï¸', 'Up-Down Arrow'),
    Emoji('â†”ï¸', 'Left-Right Arrow'),
    Emoji('â†©ï¸', 'Right Arrow Curving Left'),
    Emoji('â†ªï¸', 'Left Arrow Curving Right'),
    Emoji('â¤´ï¸', 'Right Arrow Curving Up'),
    Emoji('â¤µï¸', 'Right Arrow Curving Down'),
    Emoji('ðŸ”ƒ', 'Clockwise Vertical Arrows'),
    Emoji('ðŸ”„', 'Counterclockwise Arrows Button'),
    Emoji('ðŸ”™', 'Back Arrow'),
    Emoji('ðŸ”š', 'End Arrow'),
    Emoji('ðŸ”›', 'On! Arrow'),
    Emoji('ðŸ”œ', 'Soon Arrow'),
    Emoji('ðŸ”', 'Top Arrow'),
    Emoji('ðŸ›', 'Place of Worship'),
    Emoji('âš›ï¸', 'Atom Symbol'),
    Emoji('ðŸ•‰ï¸', 'Om'),
    Emoji('âœ¡ï¸', 'Star of David'),
    Emoji('â˜¸ï¸', 'Wheel of Dharma'),
    Emoji('â˜¯ï¸', 'Yin Yang'),
    Emoji('âœï¸', 'Latin Cross'),
    Emoji('â˜¦ï¸', 'Orthodox Cross'),
    Emoji('â˜ªï¸', 'Star and Crescent'),
    Emoji('â˜®ï¸', 'Peace Symbol'),
    Emoji('ðŸ•Ž', 'Menorah'),
    Emoji('ðŸ”¯', 'Dotted Six-Pointed Star'),
    Emoji('â™ˆ', 'Aries'),
    Emoji('â™‰', 'Taurus'),
    Emoji('â™Š', 'Gemini'),
    Emoji('â™‹', 'Cancer'),
    Emoji('â™Œ', 'Leo'),
    Emoji('â™', 'Virgo'),
    Emoji('â™Ž', 'Libra'),
    Emoji('â™', 'Scorpio'),
    Emoji('â™', 'Sagittarius'),
    Emoji('â™‘', 'Capricorn'),
    Emoji('â™’', 'Aquarius'),
    Emoji('â™“', 'Pisces'),
    Emoji('â›Ž', 'Ophiuchus'),
    Emoji('ðŸ”€', 'Shuffle Tracks Button'),
    Emoji('ðŸ”', 'Repeat Button'),
    Emoji('ðŸ”‚', 'Repeat Single Button'),
    Emoji('â–¶ï¸', 'Play Button'),
    Emoji('â©', 'Fast-Forward Button'),
    Emoji('â—€ï¸', 'Reverse Button'),
    Emoji('âª', 'Fast Reverse Button'),
    Emoji('ðŸ”¼', 'Upwards Button'),
    Emoji('â«', 'Fast Up Button'),
    Emoji('ðŸ”½', 'Downwards Button'),
    Emoji('â¬', 'Fast Down Button'),
    Emoji('â¹ï¸', 'Stop Button'),
    Emoji('âï¸', 'Eject Button'),
    Emoji('ðŸŽ¦', 'Cinema'),
    Emoji('ðŸ”…', 'Dim Button'),
    Emoji('ðŸ”†', 'Bright Button'),
    Emoji('ðŸ“¶', 'Antenna Bars'),
    Emoji('ðŸ“³', 'Vibration Mode'),
    Emoji('ðŸ“´', 'Mobile Phone Off'),
    Emoji('â™¾ï¸', 'Infinity'),
    Emoji('â™»ï¸', 'Recycling Symbol'),
    Emoji('ðŸ”±', 'Trident Emblem'),
    Emoji('ðŸ“›', 'Name Badge'),
    Emoji('ðŸ”°', 'Japanese Symbol for Beginner'),
    Emoji('â­•', 'Heavy Large Circle'),
    Emoji('âœ…', 'White Heavy Check Mark'),
    Emoji('â˜‘ï¸', 'Ballot Box With Check'),
    Emoji('âœ”ï¸', 'Heavy Check Mark'),
    Emoji('âŒ', 'Cross Mark'),
    Emoji('âŽ', 'Cross Mark Button'),
    Emoji('âž•', 'Heavy Plus Sign'),
    Emoji('âž–', 'Heavy Minus Sign'),
    Emoji('âž—', 'Heavy Division Sign'),
    Emoji('âœ–ï¸', 'Heavy Multiplication X'),
    Emoji('ðŸŸ°', 'Heavy Equals Sign'),
    Emoji('âž°', 'Curly Loop'),
    Emoji('âž¿', 'Double Curly Loop'),
    Emoji('ã€½ï¸', 'Part Alternation Mark'),
    Emoji('âœ³ï¸', 'Eight-Spoked Asterisk'),
    Emoji('âœ´ï¸', 'Eight-Pointed Star'),
    Emoji('â‡ï¸', 'Sparkle'),
    Emoji('â€¼ï¸', 'Double Exclamation Mark'),
    Emoji('â‰ï¸', 'Exclamation Question Mark'),
    Emoji('â“', 'Question Mark'),
    Emoji('â”', 'White Question Mark'),
    Emoji('â•', 'White Exclamation Mark'),
    Emoji('â—', 'Exclamation Mark'),
    Emoji('Â©ï¸', 'Copyright'),
    Emoji('Â®ï¸', 'Registered'),
    Emoji('â„¢ï¸', 'Trade Mark'),
    Emoji('#ï¸âƒ£', 'Keycap Number Sign'),
    Emoji('0ï¸âƒ£', 'Keycap Digit Zero'),
    Emoji('1ï¸âƒ£', 'Keycap Digit One'),
    Emoji('2ï¸âƒ£', 'Keycap Digit Two'),
    Emoji('3ï¸âƒ£', 'Keycap Digit Three'),
    Emoji('4ï¸âƒ£', 'Keycap Digit Four'),
    Emoji('5ï¸âƒ£', 'Keycap Digit Five'),
    Emoji('6ï¸âƒ£', 'Keycap Digit Six'),
    Emoji('7ï¸âƒ£', 'Keycap Digit Seven'),
    Emoji('8ï¸âƒ£', 'Keycap Digit Eight'),
    Emoji('9ï¸âƒ£', 'Keycap Digit Nine'),
    Emoji('ðŸ”Ÿ', 'Keycap: 10'),
    Emoji('ðŸ” ', 'Input Latin Uppercase'),
    Emoji('ðŸ”¡', 'Input Latin Lowercase'),
    Emoji('ðŸ”¢', 'Input Numbers'),
    Emoji('ðŸ”£', 'Input Symbols'),
    Emoji('ðŸ”¤', 'Input Latin Letters'),
    Emoji('ðŸ…°ï¸', 'A Button (Blood Type)'),
    Emoji('ðŸ†Ž', 'AB Button (Blood Type)'),
    Emoji('ðŸ…±ï¸', 'B Button (Blood Type)'),
    Emoji('ðŸ†‘', 'CL Button'),
    Emoji('ðŸ†’', 'Cool Button'),
    Emoji('ðŸ†“', 'Free Button'),
    Emoji('â„¹ï¸', 'Information'),
    Emoji('ðŸ†”', 'ID Button'),
    Emoji('â“‚ï¸', 'Circled M'),
    Emoji('ðŸ†•', 'New Button'),
    Emoji('ðŸ†–', 'NG Button'),
    Emoji('ðŸ…¾ï¸', 'O Button (Blood Type)'),
    Emoji('ðŸ†—', 'OK Button'),
    Emoji('ðŸ…¿ï¸', 'P Button'),
    Emoji('ðŸ†˜', 'SOS Button'),
    Emoji('ðŸ†™', 'Up! Button'),
    Emoji('ðŸ†š', 'Vs Button'),
    Emoji('ðŸˆ', 'Japanese â€œHereâ€ Button'),
    Emoji('ðŸˆ‚ï¸', 'Japanese â€œService Chargeâ€ Button'),
    Emoji('ðŸˆ·ï¸', 'Japanese â€œMonthly Amountâ€ Button'),
    Emoji('ðŸˆ¶', 'Japanese â€œNot Free of Chargeâ€ Button'),
    Emoji('ðŸˆ¯', 'Japanese â€œReservedâ€ Button'),
    Emoji('ðŸ‰', 'Japanese â€œBargainâ€ Button'),
    Emoji('ðŸˆ¹', 'Japanese â€œDiscountâ€ Button'),
    Emoji('ðŸˆš', 'Japanese â€œFree of Chargeâ€ Button'),
    Emoji('ðŸˆ²', 'Japanese â€œProhibitedâ€ Button'),
    Emoji('ðŸ‰‘', 'Japanese â€œAcceptableâ€ Button'),
    Emoji('ðŸˆ¸', 'Japanese â€œApplicationâ€ Button'),
    Emoji('ðŸˆ´', 'Japanese â€œPassing Gradeâ€ Button'),
    Emoji('ðŸˆ³', 'Japanese â€œVacancyâ€ Button'),
    Emoji('ãŠ—ï¸', 'Japanese â€œCongratulationsâ€ Button'),
    Emoji('ãŠ™ï¸', 'Japanese â€œSecretâ€ Button'),
    Emoji('ðŸˆº', 'Japanese â€œOpen for Businessâ€ Button'),
    Emoji('ðŸˆµ', 'Japanese â€œNo Vacancyâ€ Button'),
    Emoji('ðŸ”´', 'Red Circle'),
    Emoji('ðŸ”µ', 'Blue Circle'),
    Emoji('âš«', 'Black Circle'),
    Emoji('âšª', 'White Circle'),
    Emoji('â¬›', 'Black Large Square'),
    Emoji('â¬œ', 'White Large Square'),
    Emoji('â—¼ï¸', 'Black Medium Square'),
    Emoji('â—»ï¸', 'White Medium Square'),
    Emoji('â—¾', 'Black Medium-Small Square'),
    Emoji('â—½', 'White Medium-Small Square'),
    Emoji('â–ªï¸', 'Black Small Square'),
    Emoji('â–«ï¸', 'White Small Square'),
    Emoji('ðŸ”¶', 'Large Orange Diamond'),
    Emoji('ðŸ”·', 'Large Blue Diamond'),
    Emoji('ðŸ”¸', 'Small Orange Diamond'),
    Emoji('ðŸ”¹', 'Small Blue Diamond'),
    Emoji('ðŸ”º', 'Red Triangle Pointed Up'),
    Emoji('ðŸ”»', 'Red Triangle Pointed Down'),
    Emoji('ðŸ’ ', 'Diamond With a Dot'),
    Emoji('ðŸ”³', 'White Square Button'),
    Emoji('ðŸ”²', 'Black Square Button')
  ]),

// ======================================================= Category.FLAGS
  CategoryEmoji(Category.FLAGS, [
    Emoji('ðŸ', 'Chequered Flag'),
    Emoji('ðŸš©', 'Triangular Flag'),
    Emoji('ðŸŽŒ', 'Crossed Flags'),
    Emoji('ðŸ´', 'Black Flag'),
    Emoji('ðŸ³ï¸', 'White Flag'),
    Emoji('ðŸ³ï¸â€ðŸŒˆ', 'Rainbow Flag'),
    Emoji('ðŸ³ï¸â€âš§ï¸', 'Transgender Flag'),
    Emoji('ðŸ´â€â˜ ï¸', 'Pirate Flag'),
    Emoji('ðŸ‡¦ðŸ‡¨', 'Flag: Ascension Island'),
    Emoji('ðŸ‡¦ðŸ‡©', 'Flag: Andorra'),
    Emoji('ðŸ‡¦ðŸ‡ª', 'Flag: United Arab Emirates'),
    Emoji('ðŸ‡¦ðŸ‡«', 'Flag: Afghanistan'),
    Emoji('ðŸ‡¦ðŸ‡¬', 'Flag: Antigua & Barbuda'),
    Emoji('ðŸ‡¦ðŸ‡®', 'Flag: Anguilla'),
    Emoji('ðŸ‡¦ðŸ‡±', 'Flag: Albania'),
    Emoji('ðŸ‡¦ðŸ‡²', 'Flag: Armenia'),
    Emoji('ðŸ‡¦ðŸ‡´', 'Flag: Angola'),
    Emoji('ðŸ‡¦ðŸ‡¶', 'Flag: Antarctica'),
    Emoji('ðŸ‡¦ðŸ‡·', 'Flag: Argentina'),
    Emoji('ðŸ‡¦ðŸ‡¸', 'Flag: American Samoa'),
    Emoji('ðŸ‡¦ðŸ‡¹', 'Flag: Austria'),
    Emoji('ðŸ‡¦ðŸ‡º', 'Flag: Australia'),
    Emoji('ðŸ‡¦ðŸ‡¼', 'Flag: Aruba'),
    Emoji('ðŸ‡¦ðŸ‡½', 'Flag: Ã…land Islands'),
    Emoji('ðŸ‡¦ðŸ‡¿', 'Flag: Azerbaijan'),
    Emoji('ðŸ‡§ðŸ‡¦', 'Flag: Bosnia & Herzegovina'),
    Emoji('ðŸ‡§ðŸ‡§', 'Flag: Barbados'),
    Emoji('ðŸ‡§ðŸ‡©', 'Flag: Bangladesh'),
    Emoji('ðŸ‡§ðŸ‡ª', 'Flag: Belgium'),
    Emoji('ðŸ‡§ðŸ‡«', 'Flag: Burkina Faso'),
    Emoji('ðŸ‡§ðŸ‡¬', 'Flag: Bulgaria'),
    Emoji('ðŸ‡§ðŸ‡­', 'Flag: Bahrain'),
    Emoji('ðŸ‡§ðŸ‡®', 'Flag: Burundi'),
    Emoji('ðŸ‡§ðŸ‡¯', 'Flag: Benin'),
    Emoji('ðŸ‡§ðŸ‡±', 'Flag: St. BarthÃ©lemy'),
    Emoji('ðŸ‡§ðŸ‡²', 'Flag: Bermuda'),
    Emoji('ðŸ‡§ðŸ‡³', 'Flag: Brunei'),
    Emoji('ðŸ‡§ðŸ‡´', 'Flag: Bolivia'),
    Emoji('ðŸ‡§ðŸ‡¶', 'Flag: Caribbean Netherlands'),
    Emoji('ðŸ‡§ðŸ‡·', 'Flag: Brazil'),
    Emoji('ðŸ‡§ðŸ‡¸', 'Flag: Bahamas'),
    Emoji('ðŸ‡§ðŸ‡¹', 'Flag: Bhutan'),
    Emoji('ðŸ‡§ðŸ‡»', 'Flag: Bouvet Island'),
    Emoji('ðŸ‡§ðŸ‡¼', 'Flag: Botswana'),
    Emoji('ðŸ‡§ðŸ‡¾', 'Flag: Belarus'),
    Emoji('ðŸ‡§ðŸ‡¿', 'Flag: Belize'),
    Emoji('ðŸ‡¨ðŸ‡¦', 'Flag: Canada'),
    Emoji('ðŸ‡¨ðŸ‡¨', 'Flag: Cocos (Keeling) Islands'),
    Emoji('ðŸ‡¨ðŸ‡©', 'Flag: Congo - Kinshasa'),
    Emoji('ðŸ‡¨ðŸ‡«', 'Flag: Central African Republic'),
    Emoji('ðŸ‡¨ðŸ‡¬', 'Flag: Congo - Brazzaville'),
    Emoji('ðŸ‡¨ðŸ‡­', 'Flag: Switzerland'),
    Emoji('ðŸ‡¨ðŸ‡®', 'Flag: CÃ´te dâ€™Ivoire'),
    Emoji('ðŸ‡¨ðŸ‡°', 'Flag: Cook Islands'),
    Emoji('ðŸ‡¨ðŸ‡±', 'Flag: Chile'),
    Emoji('ðŸ‡¨ðŸ‡²', 'Flag: Cameroon'),
    Emoji('ðŸ‡¨ðŸ‡³', 'Flag: China'),
    Emoji('ðŸ‡¨ðŸ‡´', 'Flag: Colombia'),
    Emoji('ðŸ‡¨ðŸ‡µ', 'Flag: Clipperton Island'),
    Emoji('ðŸ‡¨ðŸ‡·', 'Flag: Costa Rica'),
    Emoji('ðŸ‡¨ðŸ‡º', 'Flag: Cuba'),
    Emoji('ðŸ‡¨ðŸ‡»', 'Flag: Cape Verde'),
    Emoji('ðŸ‡¨ðŸ‡¼', 'Flag: CuraÃ§ao'),
    Emoji('ðŸ‡¨ðŸ‡½', 'Flag: Christmas Island'),
    Emoji('ðŸ‡¨ðŸ‡¾', 'Flag: Cyprus'),
    Emoji('ðŸ‡¨ðŸ‡¿', 'Flag: Czechia'),
    Emoji('ðŸ‡©ðŸ‡ª', 'Flag: Germany'),
    Emoji('ðŸ‡©ðŸ‡¬', 'Flag: Diego Garcia'),
    Emoji('ðŸ‡©ðŸ‡¯', 'Flag: Djibouti'),
    Emoji('ðŸ‡©ðŸ‡°', 'Flag: Denmark'),
    Emoji('ðŸ‡©ðŸ‡²', 'Flag: Dominica'),
    Emoji('ðŸ‡©ðŸ‡´', 'Flag: Dominican Republic'),
    Emoji('ðŸ‡©ðŸ‡¿', 'Flag: Algeria'),
    Emoji('ðŸ‡ªðŸ‡¦', 'Flag: Ceuta & Melilla'),
    Emoji('ðŸ‡ªðŸ‡¨', 'Flag: Ecuador'),
    Emoji('ðŸ‡ªðŸ‡ª', 'Flag: Estonia'),
    Emoji('ðŸ‡ªðŸ‡¬', 'Flag: Egypt'),
    Emoji('ðŸ‡ªðŸ‡­', 'Flag: Western Sahara'),
    Emoji('ðŸ‡ªðŸ‡·', 'Flag: Eritrea'),
    Emoji('ðŸ‡ªðŸ‡¸', 'Flag: Spain'),
    Emoji('ðŸ‡ªðŸ‡¹', 'Flag: Ethiopia'),
    Emoji('ðŸ‡ªðŸ‡º', 'Flag: European Union'),
    Emoji('ðŸ‡«ðŸ‡®', 'Flag: Finland'),
    Emoji('ðŸ‡«ðŸ‡¯', 'Flag: Fiji'),
    Emoji('ðŸ‡«ðŸ‡°', 'Flag: Falkland Islands'),
    Emoji('ðŸ‡«ðŸ‡²', 'Flag: Micronesia'),
    Emoji('ðŸ‡«ðŸ‡´', 'Flag: Faroe Islands'),
    Emoji('ðŸ‡«ðŸ‡·', 'Flag: France'),
    Emoji('ðŸ‡¬ðŸ‡¦', 'Flag: Gabon'),
    Emoji('ðŸ‡¬ðŸ‡§', 'Flag: United Kingdom'),
    Emoji('ðŸ‡¬ðŸ‡©', 'Flag: Grenada'),
    Emoji('ðŸ‡¬ðŸ‡ª', 'Flag: Georgia'),
    Emoji('ðŸ‡¬ðŸ‡«', 'Flag: French Guiana'),
    Emoji('ðŸ‡¬ðŸ‡¬', 'Flag: Guernsey'),
    Emoji('ðŸ‡¬ðŸ‡­', 'Flag: Ghana'),
    Emoji('ðŸ‡¬ðŸ‡®', 'Flag: Gibraltar'),
    Emoji('ðŸ‡¬ðŸ‡±', 'Flag: Greenland'),
    Emoji('ðŸ‡¬ðŸ‡²', 'Flag: Gambia'),
    Emoji('ðŸ‡¬ðŸ‡³', 'Flag: Guinea'),
    Emoji('ðŸ‡¬ðŸ‡µ', 'Flag: Guadeloupe'),
    Emoji('ðŸ‡¬ðŸ‡¶', 'Flag: Equatorial Guinea'),
    Emoji('ðŸ‡¬ðŸ‡·', 'Flag: Greece'),
    Emoji('ðŸ‡¬ðŸ‡¸', 'Flag: South Georgia & South Sandwich Islands'),
    Emoji('ðŸ‡¬ðŸ‡¹', 'Flag: Guatemala'),
    Emoji('ðŸ‡¬ðŸ‡º', 'Flag: Guam'),
    Emoji('ðŸ‡¬ðŸ‡¼', 'Flag: Guinea-Bissau'),
    Emoji('ðŸ‡¬ðŸ‡¾', 'Flag: Guyana'),
    Emoji('ðŸ‡­ðŸ‡°', 'Flag: Hong Kong SAR China'),
    Emoji('ðŸ‡­ðŸ‡²', 'Flag: Heard & McDonald Islands'),
    Emoji('ðŸ‡­ðŸ‡³', 'Flag: Honduras'),
    Emoji('ðŸ‡­ðŸ‡·', 'Flag: Croatia'),
    Emoji('ðŸ‡­ðŸ‡¹', 'Flag: Haiti'),
    Emoji('ðŸ‡­ðŸ‡º', 'Flag: Hungary'),
    Emoji('ðŸ‡®ðŸ‡¨', 'Flag: Canary Islands'),
    Emoji('ðŸ‡®ðŸ‡©', 'Flag: Indonesia'),
    Emoji('ðŸ‡®ðŸ‡ª', 'Flag: Ireland'),
    Emoji('ðŸ‡®ðŸ‡±', 'Flag: Israel'),
    Emoji('ðŸ‡®ðŸ‡²', 'Flag: Isle of Man'),
    Emoji('ðŸ‡®ðŸ‡³', 'Flag: India'),
    Emoji('ðŸ‡®ðŸ‡´', 'Flag: British Indian Ocean Territory'),
    Emoji('ðŸ‡®ðŸ‡¶', 'Flag: Iraq'),
    Emoji('ðŸ‡®ðŸ‡·', 'Flag: Iran'),
    Emoji('ðŸ‡®ðŸ‡¸', 'Flag: Iceland'),
    Emoji('ðŸ‡®ðŸ‡¹', 'Flag: Italy'),
    Emoji('ðŸ‡¯ðŸ‡ª', 'Flag: Jersey'),
    Emoji('ðŸ‡¯ðŸ‡²', 'Flag: Jamaica'),
    Emoji('ðŸ‡¯ðŸ‡´', 'Flag: Jordan'),
    Emoji('ðŸ‡¯ðŸ‡µ', 'Flag: Japan'),
    Emoji('ðŸ‡°ðŸ‡ª', 'Flag: Kenya'),
    Emoji('ðŸ‡°ðŸ‡¬', 'Flag: Kyrgyzstan'),
    Emoji('ðŸ‡°ðŸ‡­', 'Flag: Cambodia'),
    Emoji('ðŸ‡°ðŸ‡®', 'Flag: Kiribati'),
    Emoji('ðŸ‡°ðŸ‡²', 'Flag: Comoros'),
    Emoji('ðŸ‡°ðŸ‡³', 'Flag: St. Kitts & Nevis'),
    Emoji('ðŸ‡°ðŸ‡µ', 'Flag: North Korea'),
    Emoji('ðŸ‡°ðŸ‡·', 'Flag: South Korea'),
    Emoji('ðŸ‡°ðŸ‡¼', 'Flag: Kuwait'),
    Emoji('ðŸ‡°ðŸ‡¾', 'Flag: Cayman Islands'),
    Emoji('ðŸ‡°ðŸ‡¿', 'Flag: Kazakhstan'),
    Emoji('ðŸ‡±ðŸ‡¦', 'Flag: Laos'),
    Emoji('ðŸ‡±ðŸ‡§', 'Flag: Lebanon'),
    Emoji('ðŸ‡±ðŸ‡¨', 'Flag: St. Lucia'),
    Emoji('ðŸ‡±ðŸ‡®', 'Flag: Liechtenstein'),
    Emoji('ðŸ‡±ðŸ‡°', 'Flag: Sri Lanka'),
    Emoji('ðŸ‡±ðŸ‡·', 'Flag: Liberia'),
    Emoji('ðŸ‡±ðŸ‡¸', 'Flag: Lesotho'),
    Emoji('ðŸ‡±ðŸ‡¹', 'Flag: Lithuania'),
    Emoji('ðŸ‡±ðŸ‡º', 'Flag: Luxembourg'),
    Emoji('ðŸ‡±ðŸ‡»', 'Flag: Latvia'),
    Emoji('ðŸ‡±ðŸ‡¾', 'Flag: Libya'),
    Emoji('ðŸ‡²ðŸ‡¦', 'Flag: Morocco'),
    Emoji('ðŸ‡²ðŸ‡¨', 'Flag: Monaco'),
    Emoji('ðŸ‡²ðŸ‡©', 'Flag: Moldova'),
    Emoji('ðŸ‡²ðŸ‡ª', 'Flag: Montenegro'),
    Emoji('ðŸ‡²ðŸ‡«', 'Flag: St. Martin'),
    Emoji('ðŸ‡²ðŸ‡¬', 'Flag: Madagascar'),
    Emoji('ðŸ‡²ðŸ‡­', 'Flag: Marshall Islands'),
    Emoji('ðŸ‡²ðŸ‡°', 'Flag: North Macedonia'),
    Emoji('ðŸ‡²ðŸ‡±', 'Flag: Mali'),
    Emoji('ðŸ‡²ðŸ‡²', 'Flag: Myanmar (Burma)'),
    Emoji('ðŸ‡²ðŸ‡³', 'Flag: Mongolia'),
    Emoji('ðŸ‡²ðŸ‡´', 'Flag: Macau Sar China'),
    Emoji('ðŸ‡²ðŸ‡µ', 'Flag: Northern Mariana Islands'),
    Emoji('ðŸ‡²ðŸ‡¶', 'Flag: Martinique'),
    Emoji('ðŸ‡²ðŸ‡·', 'Flag: Mauritania'),
    Emoji('ðŸ‡²ðŸ‡¸', 'Flag: Montserrat'),
    Emoji('ðŸ‡²ðŸ‡¹', 'Flag: Malta'),
    Emoji('ðŸ‡²ðŸ‡º', 'Flag: Mauritius'),
    Emoji('ðŸ‡²ðŸ‡»', 'Flag: Maldives'),
    Emoji('ðŸ‡²ðŸ‡¼', 'Flag: Malawi'),
    Emoji('ðŸ‡²ðŸ‡½', 'Flag: Mexico'),
    Emoji('ðŸ‡²ðŸ‡¾', 'Flag: Malaysia'),
    Emoji('ðŸ‡²ðŸ‡¿', 'Flag: Mozambique'),
    Emoji('ðŸ‡³ðŸ‡¦', 'Flag: Namibia'),
    Emoji('ðŸ‡³ðŸ‡¨', 'Flag: New Caledonia'),
    Emoji('ðŸ‡³ðŸ‡ª', 'Flag: Niger'),
    Emoji('ðŸ‡³ðŸ‡«', 'Flag: Norfolk Island'),
    Emoji('ðŸ‡³ðŸ‡¬', 'Flag: Nigeria'),
    Emoji('ðŸ‡³ðŸ‡®', 'Flag: Nicaragua'),
    Emoji('ðŸ‡³ðŸ‡±', 'Flag: Netherlands'),
    Emoji('ðŸ‡³ðŸ‡´', 'Flag: Norway'),
    Emoji('ðŸ‡³ðŸ‡µ', 'Flag: Nepal'),
    Emoji('ðŸ‡³ðŸ‡·', 'Flag: Nauru'),
    Emoji('ðŸ‡³ðŸ‡º', 'Flag: Niue'),
    Emoji('ðŸ‡³ðŸ‡¿', 'Flag: New Zealand'),
    Emoji('ðŸ‡´ðŸ‡²', 'Flag: Oman'),
    Emoji('ðŸ‡µðŸ‡¦', 'Flag: Panama'),
    Emoji('ðŸ‡µðŸ‡ª', 'Flag: Peru'),
    Emoji('ðŸ‡µðŸ‡«', 'Flag: French Polynesia'),
    Emoji('ðŸ‡µðŸ‡¬', 'Flag: Papua New Guinea'),
    Emoji('ðŸ‡µðŸ‡­', 'Flag: Philippines'),
    Emoji('ðŸ‡µðŸ‡°', 'Flag: Pakistan'),
    Emoji('ðŸ‡µðŸ‡±', 'Flag: Poland'),
    Emoji('ðŸ‡µðŸ‡²', 'Flag: St. Pierre & Miquelon'),
    Emoji('ðŸ‡µðŸ‡³', 'Flag: Pitcairn Islands'),
    Emoji('ðŸ‡µðŸ‡·', 'Flag: Puerto Rico'),
    Emoji('ðŸ‡µðŸ‡¸', 'Flag: Palestinian Territories'),
    Emoji('ðŸ‡µðŸ‡¹', 'Flag: Portugal'),
    Emoji('ðŸ‡µðŸ‡¼', 'Flag: Palau'),
    Emoji('ðŸ‡µðŸ‡¾', 'Flag: Paraguay'),
    Emoji('ðŸ‡¶ðŸ‡¦', 'Flag: Qatar'),
    Emoji('ðŸ‡·ðŸ‡ª', 'Flag: RÃ©union'),
    Emoji('ðŸ‡·ðŸ‡´', 'Flag: Romania'),
    Emoji('ðŸ‡·ðŸ‡¸', 'Flag: Serbia'),
    Emoji('ðŸ‡·ðŸ‡º', 'Flag: Russia'),
    Emoji('ðŸ‡·ðŸ‡¼', 'Flag: Rwanda'),
    Emoji('ðŸ‡¸ðŸ‡¦', 'Flag: Saudi Arabia'),
    Emoji('ðŸ‡¸ðŸ‡§', 'Flag: Solomon Islands'),
    Emoji('ðŸ‡¸ðŸ‡¨', 'Flag: Seychelles'),
    Emoji('ðŸ‡¸ðŸ‡©', 'Flag: Sudan'),
    Emoji('ðŸ‡¸ðŸ‡ª', 'Flag: Sweden'),
    Emoji('ðŸ‡¸ðŸ‡¬', 'Flag: Singapore'),
    Emoji('ðŸ‡¸ðŸ‡­', 'Flag: St. Helena'),
    Emoji('ðŸ‡¸ðŸ‡®', 'Flag: Slovenia'),
    Emoji('ðŸ‡¸ðŸ‡¯', 'Flag: Svalbard & Jan Mayen'),
    Emoji('ðŸ‡¸ðŸ‡°', 'Flag: Slovakia'),
    Emoji('ðŸ‡¸ðŸ‡±', 'Flag: Sierra Leone'),
    Emoji('ðŸ‡¸ðŸ‡²', 'Flag: San Marino'),
    Emoji('ðŸ‡¸ðŸ‡³', 'Flag: Senegal'),
    Emoji('ðŸ‡¸ðŸ‡´', 'Flag: Somalia'),
    Emoji('ðŸ‡¸ðŸ‡·', 'Flag: Suriname'),
    Emoji('ðŸ‡¸ðŸ‡¸', 'Flag: South Sudan'),
    Emoji('ðŸ‡¸ðŸ‡¹', 'Flag: SÃ£o TomÃ© & PrÃ­ncipe'),
    Emoji('ðŸ‡¸ðŸ‡»', 'Flag: El Salvador'),
    Emoji('ðŸ‡¸ðŸ‡½', 'Flag: Sint Maarten'),
    Emoji('ðŸ‡¸ðŸ‡¾', 'Flag: Syria'),
    Emoji('ðŸ‡¸ðŸ‡¿', 'Flag: Swaziland'),
    Emoji('ðŸ‡¹ðŸ‡¦', 'Flag: Tristan Da Cunha'),
    Emoji('ðŸ‡¹ðŸ‡¨', 'Flag: Turks & Caicos Islands'),
    Emoji('ðŸ‡¹ðŸ‡©', 'Flag: Chad'),
    Emoji('ðŸ‡¹ðŸ‡«', 'Flag: French Southern Territories'),
    Emoji('ðŸ‡¹ðŸ‡¬', 'Flag: Togo'),
    Emoji('ðŸ‡¹ðŸ‡­', 'Flag: Thailand'),
    Emoji('ðŸ‡¹ðŸ‡¯', 'Flag: Tajikistan'),
    Emoji('ðŸ‡¹ðŸ‡°', 'Flag: Tokelau'),
    Emoji('ðŸ‡¹ðŸ‡±', 'Flag: Timor-Leste'),
    Emoji('ðŸ‡¹ðŸ‡²', 'Flag: Turkmenistan'),
    Emoji('ðŸ‡¹ðŸ‡³', 'Flag: Tunisia'),
    Emoji('ðŸ‡¹ðŸ‡´', 'Flag: Tonga'),
    Emoji('ðŸ‡¹ðŸ‡·', 'Flag: Turkey'),
    Emoji('ðŸ‡¹ðŸ‡¹', 'Flag: Trinidad & Tobago'),
    Emoji('ðŸ‡¹ðŸ‡»', 'Flag: Tuvalu'),
    Emoji('ðŸ‡¹ðŸ‡¼', 'Flag: Taiwan'),
    Emoji('ðŸ‡¹ðŸ‡¿', 'Flag: Tanzania'),
    Emoji('ðŸ‡ºðŸ‡¦', 'Flag: Ukraine'),
    Emoji('ðŸ‡ºðŸ‡¬', 'Flag: Uganda'),
    Emoji('ðŸ‡ºðŸ‡²', 'Flag: U.S. Outlying Islands'),
    Emoji('ðŸ‡ºðŸ‡³', 'Flag: United Nations'),
    Emoji('ðŸ‡ºðŸ‡¸', 'Flag: United States'),
    Emoji('ðŸ‡ºðŸ‡¾', 'Flag: Uruguay'),
    Emoji('ðŸ‡ºðŸ‡¿', 'Flag: Uzbekistan'),
    Emoji('ðŸ‡»ðŸ‡¦', 'Flag: Vatican City'),
    Emoji('ðŸ‡»ðŸ‡¨', 'Flag: St. Vincent & Grenadines'),
    Emoji('ðŸ‡»ðŸ‡ª', 'Flag: Venezuela'),
    Emoji('ðŸ‡»ðŸ‡¬', 'Flag: British Virgin Islands'),
    Emoji('ðŸ‡»ðŸ‡®', 'Flag: U.S. Virgin Islands'),
    Emoji('ðŸ‡»ðŸ‡³', 'Flag: Vietnam'),
    Emoji('ðŸ‡»ðŸ‡º', 'Flag: Vanuatu'),
    Emoji('ðŸ‡¼ðŸ‡«', 'Flag: Wallis & Futuna'),
    Emoji('ðŸ‡¼ðŸ‡¸', 'Flag: Samoa'),
    Emoji('ðŸ‡½ðŸ‡°', 'Flag: Kosovo'),
    Emoji('ðŸ‡¾ðŸ‡ª', 'Flag: Yemen'),
    Emoji('ðŸ‡¾ðŸ‡¹', 'Flag: Mayotte'),
    Emoji('ðŸ‡¿ðŸ‡¦', 'Flag: South Africa'),
    Emoji('ðŸ‡¿ðŸ‡²', 'Flag: Zambia'),
    Emoji('ðŸ‡¿ðŸ‡¼', 'Flag: Zimbabwe')
  ]),
];
