import 'package:powersync/powersync.dart';
import 'package:powersync_core/powersync_core.dart';

//Generated from powersync dashboard --> Client setup
// Note powersync expects everything as SQLITE types of text,integer or real
// Casts it to appropiate type when syncing
const schema = Schema([
  Table('tasks', [
    Column.text('created_at'),
    Column.text('updated_at'),
    Column.text('name'),
    Column.integer('completed'),
    Column.text('start_date'),
    Column.text('deadline_date'),
    Column.text('my_day_snoozed_until'),
    Column.text('description'),
    Column.text('project_id'),
    Column.text('user_id'),
    Column.text('repeat_ical_rrule'),

    Column.integer('series_ended'),
    Column.integer('repeat_from_completion'),
    Column.text('review_notes'),
    Column.integer('priority'),
    Column.integer('pinned'),
    Column.text('reminder_kind'),
    Column.text('reminder_at_utc'),
    Column.integer('reminder_minutes_before_due'),
    Column.text('override_primary_value_id'),
    Column.text('override_secondary_value_id'),
  ], trackMetadata: true),
  Table('projects', [
    Column.text('name'),
    Column.text('description'),
    Column.integer('completed'),
    Column.text('created_at'),
    Column.text('updated_at'),
    Column.text('last_progress_at'),
    Column.text('user_id'),
    Column.text('start_date'),
    Column.text('deadline_date'),
    Column.text('repeat_ical_rrule'),
    Column.integer('series_ended'),
    Column.integer('repeat_from_completion'),
    Column.integer('priority'),
    Column.integer('pinned'),
    Column.text('primary_value_id'),
  ], trackMetadata: true),
  Table('project_anchor_state', [
    Column.text('user_id'),
    Column.text('project_id'),
    Column.text('last_anchored_at'),
    Column.text('created_at'),
    Column.text('updated_at'),
  ], trackMetadata: true),
  Table('routines', [
    Column.text('user_id'),
    Column.text('name'),
    Column.text('project_id'),
    Column.text('period_type'),
    Column.text('schedule_mode'),
    Column.integer('target_count'),
    Column.text('schedule_days'),
    Column.text('schedule_month_days'),
    Column.integer('schedule_time_minutes'),
    Column.integer('min_spacing_days'),
    Column.integer('rest_day_buffer'),
    Column.integer('is_active'),
    Column.text('paused_until'),
    Column.text('created_at'),
    Column.text('updated_at'),
  ], trackMetadata: true),
  Table('routine_completions', [
    Column.text('user_id'),
    Column.text('routine_id'),
    Column.text('completed_at'),
    Column.text('completed_day_local'),
    Column.integer('completed_time_local_minutes'),
    Column.text('created_at'),
  ], trackMetadata: true),
  Table('routine_skips', [
    Column.text('user_id'),
    Column.text('routine_id'),
    Column.text('period_type'),
    Column.text('period_key'),
    Column.text('created_at'),
  ], trackMetadata: true),
  Table('task_checklist_items', [
    Column.text('user_id'),
    Column.text('task_id'),
    Column.text('title'),
    Column.integer('sort_index'),
    Column.text('created_at'),
    Column.text('updated_at'),
  ], trackMetadata: true),
  Table('task_checklist_item_state', [
    Column.text('user_id'),
    Column.text('task_id'),
    Column.text('checklist_item_id'),
    Column.text('occurrence_date'),
    Column.integer('is_checked'),
    Column.text('checked_at'),
    Column.text('created_at'),
    Column.text('updated_at'),
  ], trackMetadata: true),
  Table('routine_checklist_items', [
    Column.text('user_id'),
    Column.text('routine_id'),
    Column.text('title'),
    Column.integer('sort_index'),
    Column.text('created_at'),
    Column.text('updated_at'),
  ], trackMetadata: true),
  Table('routine_checklist_item_state', [
    Column.text('user_id'),
    Column.text('routine_id'),
    Column.text('checklist_item_id'),
    Column.text('period_type'),
    Column.text('window_key'),
    Column.integer('is_checked'),
    Column.text('checked_at'),
    Column.text('created_at'),
    Column.text('updated_at'),
  ], trackMetadata: true),
  Table('checklist_events', [
    Column.text('user_id'),
    Column.text('parent_type'),
    Column.text('parent_id'),
    Column.text('checklist_item_id'),
    Column.text('scope_period_type'),
    Column.text('scope_date'),
    Column.text('event_type'),
    Column.text('metrics_json'),
    Column.text('created_at'),
  ], trackMetadata: true),
  Table('values', [
    Column.text('name'),
    Column.text('color'),
    Column.text('created_at'),
    Column.text('updated_at'),
    Column.text('user_id'),
    Column.text('icon_name'),
    Column.text('priority'),
  ], trackMetadata: true),
  Table('value_ratings_weekly', [
    Column.text('user_id'),
    Column.text('value_id'),
    Column.text('week_start'),
    Column.integer('rating'),
    Column.text('created_at'),
    Column.text('updated_at'),
  ], trackMetadata: true),
  Table(
    'user_profiles',
    [
      Column.text('user_id'),
      Column.text('settings_overrides'),
      Column.text('created_at'),
      Column.text('updated_at'),
    ],
    ignoreEmptyUpdates: true,
    trackMetadata: true,
  ),
  Table('my_day_days', [
    Column.text('user_id'),
    Column.text('day_utc'),
    Column.text('ritual_completed_at'),
    Column.text('created_at'),
    Column.text('updated_at'),
  ], trackMetadata: true),
  Table('my_day_picks', [
    Column.text('user_id'),
    Column.text('day_id'),
    Column.text('task_id'),
    Column.text('routine_id'),
    Column.text('bucket'),
    Column.integer('sort_index'),
    Column.text('picked_at'),
    Column.integer('suggestion_rank'),
    Column.text('qualifying_value_id'),
    Column.text('reason_codes'),
    Column.text('created_at'),
    Column.text('updated_at'),
  ], trackMetadata: true),
  Table('pending_notifications', [
    Column.text('user_id'),
    Column.text('scheduled_for'),
    Column.text('status'),
    Column.text('payload'),
    Column.text('created_at'),
    Column.text('delivered_at'),
    Column.text('seen_at'),
    Column.text('screen_key'),
  ], trackMetadata: true),
  Table('attention_rules', [
    Column.text('rule_key'),
    Column.text('user_id'),
    Column.text('domain'),
    Column.text('bucket'),
    Column.text('evaluator'),
    Column.text('evaluator_params'),
    Column.text('severity'),
    Column.text('display_config'),
    Column.text('resolution_actions'),
    Column.integer('active'),
    Column.text('created_at'),
    Column.text('updated_at'),
    Column.text('source'),
  ], trackMetadata: true),
  Table('attention_rule_runtime_state', [
    Column.text('user_id'),
    Column.text('rule_id'),
    Column.text('entity_type'),
    Column.text('entity_id'),
    Column.text('state_hash'),
    Column.text('dismissed_state_hash'),
    Column.text('last_evaluated_at'),
    Column.text('next_evaluate_after'),
    Column.text('metadata'),
    Column.text('created_at'),
    Column.text('updated_at'),
  ], trackMetadata: true),
  Table('task_completion_history', [
    Column.text('task_id'),
    Column.text('occurrence_date'),
    Column.text('original_occurrence_date'),
    Column.text('completed_at'),
    Column.text('notes'),
    Column.text('user_id'),
    Column.text('created_at'),
    Column.text('updated_at'),
  ], trackMetadata: true),
  Table('task_snooze_events', [
    Column.text('user_id'),
    Column.text('task_id'),
    Column.text('snoozed_at'),
    Column.text('snoozed_until'),
    Column.text('created_at'),
    Column.text('updated_at'),
  ], trackMetadata: true),
  Table('project_completion_history', [
    Column.text('project_id'),
    Column.text('occurrence_date'),
    Column.text('original_occurrence_date'),
    Column.text('completed_at'),
    Column.text('notes'),
    Column.text('user_id'),
    Column.text('created_at'),
    Column.text('updated_at'),
  ], trackMetadata: true),
  Table('task_recurrence_exceptions', [
    Column.text('task_id'),
    Column.text('original_date'),
    Column.text('exception_type'),
    Column.text('new_date'),
    Column.text('new_deadline'),
    Column.text('created_at'),
    Column.text('updated_at'),
    Column.text('user_id'),
  ], trackMetadata: true),
  Table('project_recurrence_exceptions', [
    Column.text('project_id'),
    Column.text('original_date'),
    Column.text('exception_type'),
    Column.text('new_date'),
    Column.text('new_deadline'),
    Column.text('created_at'),
    Column.text('updated_at'),
    Column.text('user_id'),
  ], trackMetadata: true),
  Table('attention_resolutions', [
    Column.text('user_id'),
    Column.text('rule_id'),
    Column.text('entity_id'),
    Column.text('entity_type'),
    Column.text('resolved_at'),
    Column.text('resolution_action'),
    Column.text('action_details'),
    Column.text('created_at'),
  ], trackMetadata: true),
  Table('analytics_snapshots', [
    Column.text('user_id'),
    Column.text('entity_type'),
    Column.text('entity_id'),
    Column.text('snapshot_date'),
    Column.text('metrics'),
    Column.text('created_at'),
  ]),
  Table('analytics_correlations', [
    Column.text('user_id'),
    Column.text('correlation_type'),
    Column.text('source_type'),
    Column.text('source_id'),
    Column.text('target_type'),
    Column.text('target_id'),
    Column.text('period_start'),
    Column.text('period_end'),
    Column.text('coefficient'),
    Column.integer('sample_size'),
    Column.text('strength'),
    Column.text('insight'),
    Column.text('value_with_source'),
    Column.text('value_without_source'),
    Column.text('computed_at'),
    Column.text('statistical_significance'),
    Column.text('performance_metrics'),
  ]),
  Table('analytics_insights', [
    Column.text('user_id'),
    Column.text('insight_type'),
    Column.text('title'),
    Column.text('description'),
    Column.text('metadata'),
    Column.text('score'),
    Column.text('confidence'),
    Column.integer('is_positive'),
    Column.text('generated_at'),
    Column.text('period_start'),
    Column.text('period_end'),
    Column.text('created_at'),
  ]),
  Table('journal_entries', [
    Column.text('user_id'),
    Column.text('entry_date'),
    Column.text('entry_time'),
    Column.text('journal_text'),
    Column.text('created_at'),
    Column.text('updated_at'),
    Column.text('deleted_at'),
    Column.text('occurred_at'),
    Column.text('local_date'),
  ], trackMetadata: true),

  // Tracker Groups (user-defined organizational groups)
  Table('tracker_groups', [
    Column.text('user_id'),
    Column.text('name'),
    Column.integer('sort_order'),
    Column.integer('is_active'),
    Column.text('created_at'),
    Column.text('updated_at'),
  ], trackMetadata: true),

  // Tracker model (OPT-A): event-log + projections
  Table('tracker_definitions', [
    Column.text('user_id'),
    Column.text('group_id'),
    Column.text('name'),
    Column.text('description'),
    Column.text('scope'),
    Column.text('roles'),
    Column.text('value_type'),
    Column.text('config'),
    Column.text('goal'),
    Column.integer('is_active'),
    Column.integer('sort_order'),
    Column.text('created_at'),
    Column.text('updated_at'),
    Column.text('deleted_at'),
    Column.text('source'),
    Column.text('system_key'),
    Column.text('op_kind'),
    Column.text('value_kind'),
    Column.text('unit_kind'),
    Column.integer('min_int'),
    Column.integer('max_int'),
    Column.integer('step_int'),
    Column.text('linked_value_id'),
    Column.integer('is_outcome'),
    Column.integer('is_insight_enabled'),
    Column.integer('higher_is_better'),
  ], trackMetadata: true),
  Table('tracker_preferences', [
    Column.text('user_id'),
    Column.text('tracker_id'),
    Column.integer('is_active'),
    Column.integer('sort_order'),
    Column.integer('pinned'),
    Column.integer('show_in_quick_add'),
    Column.text('color'),
    Column.text('created_at'),
    Column.text('updated_at'),
  ], trackMetadata: true),
  Table('tracker_definition_choices', [
    Column.text('user_id'),
    Column.text('tracker_id'),
    Column.text('choice_key'),
    Column.text('label'),
    Column.integer('sort_order'),
    Column.integer('is_active'),
    Column.text('created_at'),
    Column.text('updated_at'),
  ]),
  Table('tracker_events', [
    Column.text('user_id'),
    Column.text('tracker_id'),
    Column.text('anchor_type'),
    Column.text('entry_id'),
    Column.text('anchor_date'),
    Column.text('op'),
    Column.text('value'),
    Column.text('occurred_at'),
    Column.text('recorded_at'),
  ], trackMetadata: true),
  Table('tracker_state_day', [
    Column.text('user_id'),
    Column.text('anchor_type'),
    Column.text('anchor_date'),
    Column.text('tracker_id'),
    Column.text('value'),
    Column.text('last_event_id'),
    Column.text('updated_at'),
  ]),
  Table('tracker_state_entry', [
    Column.text('user_id'),
    Column.text('entry_id'),
    Column.text('tracker_id'),
    Column.text('value'),
    Column.text('last_event_id'),
    Column.text('updated_at'),
  ]),
]);
